// generated by lazyTool build64k.cpp from .\clear_only_test.lt
//
// This file is a procedural-only standalone player. It contains no model files,
// no texture files and no editor UI. Geometry is either produced by the shader
// from SV_VertexID or by the tiny built-in primitive vertex buffers below.
// Kept features: clear-only command playback.
#define WIN32_LEAN_AND_MEAN
#define COBJMACROS
#include <windows.h>
#include <stddef.h>
#include <d3d11.h>
#define LT_WNDCLS "lt64k_window"
#define LT_PI 3.14159265358979323846f
// -----------------------------------------------------------------------------
// Project export settings copied from the .lt file. The 64k player assumes
// fullscreen borderless mode and does not support debug HUD/build overrides.
// W/H and RW/RH are always the fullscreen monitor/backbuffer size. That keeps
// the projection aspect, scene depth, scene-scaled render targets, and final
// output in the same resolution space. Fixed custom RTs still keep the size
// authored in the .lt file when scene_scale_divisor == 0.
// -----------------------------------------------------------------------------
#define LT_PROJECT_W 1280
#define LT_PROJECT_H 720
#define LT_SHADOW_W 1024
#define LT_SHADOW_H 1024
#define LT_VSYNC 0
#define LT_ESC_CLOSE 0
#define LT_EXIT_AFTER_TIMELINE 0
#define LT_SHOW_FPS_TITLE 0
// Minimal CRT replacements and tiny math types. /NODEFAULTLIB builds need these.
int _fltused=0;
typedef unsigned int u32;
void* __cdecl memset(void* d, int c, size_t n) {
    unsigned char* p=(unsigned char*)d;
    while(n--)*p++=(unsigned char)c;
    return d;
}
void* __cdecl memcpy(void* d, const void* s, size_t n) {
    unsigned char* p=(unsigned char*)d;
    const unsigned char* q=(const unsigned char*)s;
    while(n--)*p++=*q++;
    return d;
}
// Global D3D handles and runtime sizes. This player is fullscreen-only, so
// W/H are the monitor/backbuffer size and RW/RH intentionally equal W/H.
// Camera projection, scene depth and scene-scaled render textures all use
// this fullscreen size. Only fixed custom RTs keep their authored dimensions.
static ID3D11Device* dev;
static ID3D11DeviceContext* ctx;
static IDXGISwapChain* swp;
static ID3D11RenderTargetView* rtv;
static HWND wh;
static int W, H;
// Flattened render commands. Resource names are gone here; everything is a
// small integer code so the runtime can be straightforward and deterministic.
typedef struct {
    int type, enabled, shader, shs, topology, mk, vc, ic, ccen, cden, ccs, dcs, rt, dep, dt, dw, ab, cb, cw, scast, srecv, pst, pc, tc, sc, uc, dispatch_src, tx, ty, tz, reset;
    int tex[8], tsl[8], srv[8], ssl[8], uav[8], usl[8];
    float cc[4], dc, pos[3], q[4], scl[3];
} Cmd;
static Cmd cmd[1] = {
    {
        1, 1, -1, -1, 0, 0, 3, 1, 1, 0, -1, -1, -2, -1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, -1, 1, 1, 1, 0, {
            -1, -1, -1, -1, -1, -1, -1, -1
        }, {
            0, 0, 0, 0, 0, 0, 0, 0
        }, {
            -1, -1, -1, -1, -1, -1, -1, -1
        }, {
            0, 0, 0, 0, 0, 0, 0, 0
        }, {
            -1, -1, -1, -1, -1, -1, -1, -1
        }, {
            0, 0, 0, 0, 0, 0, 0, 0
        }, {
            0.0799999982f, 0.180000007f, 0.319999993f, 1.0f
        }, 1.0f, {
            0.0f, 0.0f, 0.0f
        }, {
            0.0f, 0.0f, 0.0f, 1.0f
        }, {
            1.0f, 1.0f, 1.0f
        }
    },
};
typedef struct {
    int type, enabled, src, src_cmd;
    int iv[4];
    float fv[4];
} Par;
static Par par[1] = {
    {
        0, 0, 0, -1, {
            0, 0, 0, 0
        }, {
            0.0f, 0.0f, 0.0f, 0.0f
        }
    },
};
typedef struct {
    int type, src, src_cmd;
    int iv[4];
    float fv[4];
} Uv;
static Uv uv[1] = {
    {
        0, 0, -1, {
            0, 0, 0, 0
        }, {
            0.0f, 0.0f, 0.0f, 0.0f
        }
    },
};
enum {
    CMDN=1, SHN=0, RTN=0, SBN=0, UVN=0, PN=0, TLN=0, TRN=0, KEYN=0, TL_LOOP=0, TL_ON=0
};
static void zmem(void* p, int n) {
    unsigned char* b=(unsigned char*)p;
    while(n--)*b++=0;
}
static void clear_vals(Cmd* c, float* cc) {
    int i;
    for(i=0;i<4;i++)cc[i]=c->cc[i];
    if(c->ccs>=0&&c->ccs<UVN&&uv[c->ccs].type==7)for(i=0;i<4;i++)cc[i]=uv[c->ccs].fv[i];
}
static void fps_title(void) {
}
static void render(float sec) {
    (void)sec;
    for(int i=0;i<CMDN;i++) {
        Cmd* c=cmd+i;
        if(c->enabled&&c->type==1&&c->rt==-2&&c->ccen) {
            float cc[4];
            clear_vals(c, cc);
            ID3D11DeviceContext_ClearRenderTargetView(ctx, rtv, cc);
        }
    }
    IDXGISwapChain_Present(swp, LT_VSYNC?1:0, 0);
    fps_title();
}
static LRESULT CALLBACK wp(HWND h, UINT m, WPARAM w, LPARAM l) {
    if(LT_ESC_CLOSE&&m==WM_KEYDOWN&&w==VK_ESCAPE)PostQuitMessage(0);
    if(m==WM_CLOSE||m==WM_DESTROY) {
        PostQuitMessage(0);
        return 0;
    }
    return DefWindowProcA(h, m, w, l);
}
static float qpcdt(LARGE_INTEGER* now, LARGE_INTEGER* prev, LARGE_INTEGER* freq) {
    unsigned int dt=(unsigned int)now->LowPart-(unsigned int)prev->LowPart;
    unsigned int fq=(unsigned int)freq->LowPart? (unsigned int)freq->LowPart:1;
    float s=(float)dt/(float)fq;
    if(s>0.10f)s=0.10f;
    return s;
}
void WINAPI WinMainCRTStartup(void) {
    WNDCLASSA wc;
    zmem(&wc, sizeof(wc));
    wc.lpfnWndProc=wp;
    wc.hInstance=GetModuleHandleA(0);
    wc.hCursor=LoadCursorA(0, (LPCSTR)32512);
    wc.lpszClassName=LT_WNDCLS;
    RegisterClassA(&wc);
    W=GetSystemMetrics(SM_CXSCREEN);
    H=GetSystemMetrics(SM_CYSCREEN);
    HWND hw=CreateWindowExA(WS_EX_TOPMOST, LT_WNDCLS, "lt64k", WS_POPUP|WS_VISIBLE, 0, 0, W, H, 0, 0, wc.hInstance, 0);
    wh=hw;
    SetWindowPos(hw, HWND_TOPMOST, 0, 0, W, H, SWP_SHOWWINDOW);
    while(ShowCursor(FALSE)>=0);
    DXGI_SWAP_CHAIN_DESC sd;
    zmem(&sd, sizeof(sd));
    sd.BufferCount=1;
    sd.BufferDesc.Width=W;
    sd.BufferDesc.Height=H;
    sd.BufferDesc.Format=DXGI_FORMAT_R8G8B8A8_UNORM;
    sd.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;
    sd.OutputWindow=hw;
    sd.SampleDesc.Count=1;
    sd.Windowed=TRUE;
    if(FAILED(D3D11CreateDeviceAndSwapChain(0, D3D_DRIVER_TYPE_HARDWARE, 0, 0, 0, 0, D3D11_SDK_VERSION, &sd, &swp, &dev, 0, &ctx)))ExitProcess(1);
    ID3D11Texture2D* bb=0;
    IDXGISwapChain_GetBuffer(swp, 0, &IID_ID3D11Texture2D, (void**)&bb);
    ID3D11Device_CreateRenderTargetView(dev, (ID3D11Resource*)bb, 0, &rtv);
    ID3D11Texture2D_Release(bb);
    LARGE_INTEGER fq, t0, tn;
    QueryPerformanceFrequency(&fq);
    QueryPerformanceCounter(&t0);
    float sec=0;
    MSG msg;
    for(;;) {
        while(PeekMessageA(&msg, 0, 0, 0, PM_REMOVE)) {
            if(msg.message==WM_QUIT)ExitProcess(0);
            TranslateMessage(&msg);
            DispatchMessageA(&msg);
        }
        QueryPerformanceCounter(&tn);
        sec+=qpcdt(&tn, &t0, &fq);
        t0=tn;
        render(sec);
    }
}

