// generated by lazyTool build64k.cpp from ..\projects\test2.lt
#define WIN32_LEAN_AND_MEAN
#define COBJMACROS
#include <windows.h>
#include <stddef.h>
#include <d3d11.h>
#include <d3dcompiler.h>
#define LT_WNDCLS "lt64k_window"
#define LT_PI 3.14159265358979323846f
int _fltused=0;
typedef unsigned int u32;
typedef struct {
    float m[16];
} M4;
void* __cdecl memset(void* d, int c, size_t n) {
    unsigned char* p=(unsigned char*)d;
    while(n--)*p++=(unsigned char)c;
    return d;
}
void* __cdecl memcpy(void* d, const void* s, size_t n) {
    unsigned char* p=(unsigned char*)d;
    const unsigned char* q=(const unsigned char*)s;
    while(n--)*p++=*q++;
    return d;
}
typedef struct {
    float view_proj[16];
    float time_vec[4];
    float light_dir[4];
    float light_color[4];
    float cam_pos[4];
    float shadow_view_proj[16];
    float inv_view_proj[16];
    float prev_view_proj[16];
    float prev_inv_view_proj[16];
    float prev_shadow_view_proj[16];
    float cam_dir[4];
    float shadow_cascade_splits[4];
    float shadow_params[4];
    float shadow_cascade_rects[4][4];
    float shadow_cascade_view_proj[4][16];
} SceneCB;
typedef struct {
    float slots[64][4];
} UserCB;
typedef struct {
    float world[16];
} ObjectCB;
static ID3D11Device* dev;
static ID3D11DeviceContext* ctx;
static IDXGISwapChain* swp;
static ID3D11RenderTargetView* rtv;
static ID3D11DepthStencilView* dsv;
static ID3D11Buffer* scene_cb;
static ID3D11Buffer* object_cb;
static ID3D11Buffer* user_cb;
static ID3D11Buffer* prim_vb[5];
static int W, H;
typedef struct {
    const char* src;
    unsigned int len;
    ID3D11VertexShader* vs;
    ID3D11PixelShader* ps;
    ID3D11InputLayout* il;
} Sh;
static const char sh_src_0[] =
"// Minimal example shader used by the default scene. It now samples the shared\n"
"// shadow atlas and uses the cascade data exposed through SceneCB.\n"
"cbuffer SceneCB : register(b0)\n"
"{\n"
"    float4x4 ViewProj;\n"
"    float4 TimeVec;\n"
"    float4 LightDir;\n"
"    float4 LightColor;\n"
"    float4 CamPos;\n"
"    float4x4 ShadowViewProj;\n"
"    float4x4 InvViewProj;\n"
"    float4x4 PrevViewProj;\n"
"    float4x4 PrevInvViewProj;\n"
"    float4x4 PrevShadowViewProj;\n"
"    float4 CamDir;\n"
"    float4 ShadowCascadeSplits;\n"
"    float4 ShadowParams;\n"
"    float4 ShadowCascadeRects[4];\n"
"    float4x4 ShadowCascadeViewProj[4];\n"
"};\n"
"\n"
"cbuffer ObjectCB : register(b1)\n"
"{\n"
"    float4x4 World;\n"
"};\n"
"\n"
"Texture2D ShadowMap : register(t7);\n"
"SamplerComparisonState ShadowSampler : register(s1);\n"
"\n"
"struct VSIn {\n"
"    float3 pos : POSITION;\n"
"    float3 nor : NORMAL;\n"
"    float2 uv  : TEXCOORD0;\n"
"};\n"
"\n"
"struct VSOut {\n"
"    float4 pos  : SV_POSITION;\n"
"    float3 nor  : NORMAL;\n"
"    float3 wpos : TEXCOORD0;\n"
"};\n"
"\n"
"VSOut VSMain(VSIn v) {\n"
"    VSOut o;\n"
"    float4 wpos = mul(World, float4(v.pos, 1.0));\n"
"    o.pos = mul(ViewProj, wpos);\n"
"    o.wpos = wpos.xyz;\n"
"    o.nor = normalize(mul(World, float4(v.nor, 0.0)).xyz);\n"
"    return o;\n"
"}\n"
"\n"
"float sample_shadow_cascade(int cascade_index, float3 wpos, float ndl) {\n"
"    uint shadow_w = 0;\n"
"    uint shadow_h = 0;\n"
"    ShadowMap.GetDimensions(shadow_w, shadow_h);\n"
"    if (shadow_w == 0 || shadow_h == 0)\n"
"        return 1.0;\n"
"\n"
"    float4 shadow_clip = mul(ShadowCascadeViewProj[cascade_index], float4(wpos, 1.0));\n"
"    if (abs(shadow_clip.w) < 1e-5)\n"
"        return 1.0;\n"
"\n"
"    float3 shadow_ndc = shadow_clip.xyz / shadow_clip.w;\n"
"    float2 uv_local = float2(shadow_ndc.x * 0.5 + 0.5, shadow_ndc.y * -0.5 + 0.5);\n"
"    if (uv_local.x < 0.0 || uv_local.x > 1.0 || uv_local.y < 0.0 || uv_local.y > 1.0)\n"
"        return 1.0;\n"
"    if (shadow_ndc.z < 0.0 || shadow_ndc.z > 1.0)\n"
"        return 1.0;\n"
"\n"
"    float4 rect = ShadowCascadeRects[cascade_index];\n"
"    float2 atlas_uv = uv_local * rect.xy + rect.zw;\n"
"    float bias = lerp(0.0025, 0.0003, saturate(ndl));\n"
"    return ShadowMap.SampleCmpLevelZero(ShadowSampler, atlas_uv, shadow_ndc.z - bias);\n"
"}\n"
"\n"
"int select_shadow_cascade(float3 wpos) {\n"
"    int cascade_count = clamp((int)ShadowParams.x, 1, 4);\n"
"    float view_depth = dot(wpos - CamPos.xyz, CamDir.xyz);\n"
"    int cascade_index = 0;\n"
"    [unroll]\n"
"    for (int i = 0; i < 3; i++) {\n"
"        if (i + 1 < cascade_count && view_depth > ShadowCascadeSplits[i])\n"
"            cascade_index = i + 1;\n"
"    }\n"
"    return cascade_index;\n"
"}\n"
"\n"
"float4 PSMain(VSOut i) : SV_Target {\n"
"    float3 n = normalize(i.nor);\n"
"    float3 ld = normalize(-LightDir.xyz);\n"
"    float ndl = saturate(dot(n, ld));\n"
"    int cascade_index = select_shadow_cascade(i.wpos);\n"
"    float shadow = sample_shadow_cascade(cascade_index, i.wpos, ndl);\n"
"\n"
"    float3 base = 0.30 + 0.70 * (0.5 + 0.5 * n);\n"
"    float3 sun = LightColor.xyz * LightDir.w * ndl * shadow;\n"
"    float3 ambient = float3(0.06, 0.065, 0.08);\n"
"    return float4(base * (ambient + sun), 1.0);\n"
"}\n"
"";
static Sh sh[1] = {
    {
        sh_src_0, sizeof(sh_src_0)-1, 0, 0, 0
    },
};
typedef struct {
    int type, enabled, shader, topology, mk, vc, ic, ccen, cden;
    float cc[4], dc, pos[3], q[4], scl[3];
} Cmd;
static Cmd cmd[3] = {
    {
        1, 1, -1, 1, 0, 3, 1, 1, 1, {
            0.0399999991f, 0.0199999996f, 0.0f, 1.0f
        }, 1.0f, {
            0.0f, 0.0f, 0.0f
        }, {
            0.0f, 0.0f, 0.0f, 1.0f
        }, {
            1.0f, 1.0f, 1.0f
        }
    },
    {
        2, 1, 0, 1, 1, 36, 1, 1, 1, {
            0.0500000007f, 0.0500000007f, 0.0799999982f, 1.0f
        }, 1.0f, {
            0.0f, 0.0f, 0.0f
        }, {
            0.0f, 0.0f, 0.0f, 1.0f
        }, {
            1.0f, 1.0f, 1.0f
        }
    },
    {
        2, 1, 0, 1, 1, 36, 1, 1, 1, {
            0.0500000007f, 0.0500000007f, 0.0799999982f, 1.0f
        }, 1.0f, {
            0.0f, -2.0f, 0.0f
        }, {
            0.0f, 0.0f, 0.0f, 1.0f
        }, {
            5.0f, 0.100000001f, 5.0f
        }
    },
};
typedef struct {
    int type, src, src_cmd;
    int iv[4];
    float fv[4];
} Uv;
static Uv uv[2] = {
    {
        7, 0, -1, {
            0, 0, 0, 0
        }, {
            0.0f, 0.0f, 0.0f, 0.0f
        }
    },
    {
        6, 0, -1, {
            0, 0, 0, 0
        }, {
            1.0f, 0.0f, 0.0f, 0.0f
        }
    },
};
typedef struct {
    int fr;
    int iv[4];
    float fv[16];
} Key;
typedef struct {
    int kind, target, type, integral, start, count, enabled;
} Tr;
static Key key[8] = {
    {
        0, {
            0, 0, 0, 0
        }, {
            9.08301926f, 4.67694998f, 0.180185124f, -1.59869432f, -0.400479645f, 1.04700005f, 0.00100000005f, 100.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
        }
    },
    {
        10, {
            0, 0, 0, 0
        }, {
            -0.551251292f, 16.3368721f, 16.4349747f, 3.12448597f, -0.910479546f, 1.04700005f, 0.00100000005f, 100.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
        }
    },
    {
        20, {
            0, 0, 0, 0
        }, {
            -5.42498684f, 1.19592237f, -0.173835978f, 1.57948172f, -0.430479378f, 1.04700005f, 0.00100000005f, 100.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
        }
    },
    {
        30, {
            0, 0, 0, 0
        }, {
            0.379143685f, 4.86137056f, -8.38254356f, -0.0255179014f, -0.625479281f, 1.04700005f, 0.00100000005f, 100.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
        }
    },
    {
        40, {
            0, 0, 0, 0
        }, {
            9.08301926f, 4.67694998f, 0.180185124f, -1.59869432f, -0.400479645f, 1.04700005f, 0.00100000005f, 100.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
        }
    },
    {
        0, {
            0, 0, 0, 0
        }, {
            0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
        }
    },
    {
        8, {
            0, 0, 0, 0
        }, {
            1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
        }
    },
    {
        18, {
            0, 0, 0, 0
        }, {
            0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
        }
    },
};
static Tr tr[2] = {
    {
        4, -1, 0, 0, 0, 5, 1
    },
    {
        1, 1, 6, 0, 5, 3, 1
    },
};
static float cam[8]= {
    1.37560272f, 14.0048866f, 13.1840172f, -2.84669852f, -0.808479548f, 1.04700005f, 0.00100000005f, 100.0f
};
static float dl[10]= {
    5.7735033f, 5.7735033f, 5.7735033f, 0.0f, 0.0f, 0.0f, 1.0f, 0.898999989f, 0.899999976f, 1.0f
};
enum {
    CMDN=3, SHN=1, UVN=2, TRN=2, KEYN=8, TL_FPS=7, TL_LEN=41, TL_LOOP=1, TL_ON=1, TL_LERP=0
};
static void zmem(void* p, int n) {
    unsigned char* b=(unsigned char*)p;
    while(n--)*b++=0;
}
static void cpy(void* d, const void* s, int n) {
    unsigned char* a=(unsigned char*)d;
    const unsigned char* b=(const unsigned char*)s;
    while(n--)*a++=*b++;
}
static float ab(float x) {
    return x<0?-x:x;
}
static float cl(float x, float a, float b) {
    return x<a?a:(x>b?b:x);
}
static float wrap(float x) {
    while(x>LT_PI)x-=6.28318530718f;
    while(x<-LT_PI)x+=6.28318530718f;
    return x;
}
static float sn(float x) {
    x=wrap(x);
    float x2=x*x;
    return x*(1.0f-x2*(0.166666667f-x2*(0.00833333333f-x2*0.000198412698f)));
}
static float cs(float x) {
    return sn(x+1.57079632679f);
}
static float lerp(float a, float b, float t) {
    return a+(b-a)*t;
}
static float lerpa(float a, float b, float t) {
    float d=wrap(b-a);
    return wrap(a+d*t);
}
static float rsq(float x) {
    union {
        float f;
        unsigned int i;
    }
    u;
    float xh=x*0.5f;
    if(x<=0) return 0;
    u.f=x;
    u.i=0x5f3759df-(u.i>>1);
    u.f=u.f*(1.5f-xh*u.f*u.f);
    return u.f;
}
static float sqt(float x) {
    return x<=0?0:x*rsq(x);
}
typedef struct {
    float x, y, z, w;
} Q;
static void mid(M4* m) {
    zmem(m, sizeof(M4));
    m->m[0]=m->m[5]=m->m[10]=m->m[15]=1;
}
static M4 mmul(M4 a, M4 b) {
    M4 r;
    int row, col, k;
    zmem(&r, sizeof(r));
    for(row=0;row<4;row++)for(col=0;col<4;col++)for(k=0;k<4;k++)r.m[row*4+col]+=a.m[row*4+k]*b.m[k*4+col];
    return r;
}
static void rotxyz(float* rr, M4* out) {
    float cx=cs(rr[0]), sx=sn(rr[0]), cy=cs(rr[1]), sy=sn(rr[1]), cz=cs(rr[2]), sz=sn(rr[2]);
    M4 rx, ry, rz;
    mid(&rx);
    mid(&ry);
    mid(&rz);
    rx.m[5]=cx;
    rx.m[6]=sx;
    rx.m[9]=-sx;
    rx.m[10]=cx;
    ry.m[0]=cy;
    ry.m[2]=-sy;
    ry.m[8]=sy;
    ry.m[10]=cy;
    rz.m[0]=cz;
    rz.m[1]=sz;
    rz.m[4]=-sz;
    rz.m[5]=cz;
    *out=mmul(mmul(rx, ry), rz);
}
static Q qn(Q q) {
    float l=q.x*q.x+q.y*q.y+q.z*q.z+q.w*q.w;
    if(l<0.00000001f) {
        q.x=q.y=q.z=0;
        q.w=1;
        return q;
    }
    float r=rsq(l);
    q.x*=r;
    q.y*=r;
    q.z*=r;
    q.w*=r;
    return q;
}
static Q qfm(M4* m) {
    Q q;
    float m00=m->m[0], m01=m->m[1], m02=m->m[2], m10=m->m[4], m11=m->m[5], m12=m->m[6], m20=m->m[8], m21=m->m[9], m22=m->m[10], tr=m00+m11+m22, s;
    q.x=q.y=q.z=0;
    q.w=1;
    if(tr>0) {
        s=sqt(tr+1.0f)*2.0f;
        q.w=0.25f*s;
        q.x=(m12-m21)/s;
        q.y=(m20-m02)/s;
        q.z=(m01-m10)/s;
    }
    else if(m00>m11&&m00>m22) {
        s=sqt(1.0f+m00-m11-m22)*2.0f;
        q.w=(m12-m21)/s;
        q.x=0.25f*s;
        q.y=(m01+m10)/s;
        q.z=(m20+m02)/s;
    }
    else if(m11>m22) {
        s=sqt(1.0f+m11-m00-m22)*2.0f;
        q.w=(m20-m02)/s;
        q.x=(m01+m10)/s;
        q.y=0.25f*s;
        q.z=(m12+m21)/s;
    }
    else {
        s=sqt(1.0f+m22-m00-m11)*2.0f;
        q.w=(m01-m10)/s;
        q.x=(m20+m02)/s;
        q.y=(m12+m21)/s;
        q.z=0.25f*s;
    }
    return qn(q);
}
static Q qfe(float* r) {
    M4 m;
    rotxyz(r, &m);
    return qfm(&m);
}
static Q qfa(float* r) {
    Q q;
    q.x=r[0];
    q.y=r[1];
    q.z=r[2];
    q.w=r[3];
    return qn(q);
}
static Q ql(Q a, Q b, float t) {
    Q q;
    float d;
    a=qn(a);
    b=qn(b);
    d=a.x*b.x+a.y*b.y+a.z*b.z+a.w*b.w;
    if(d<0) {
        b.x=-b.x;
        b.y=-b.y;
        b.z=-b.z;
        b.w=-b.w;
    }
    q.x=lerp(a.x, b.x, t);
    q.y=lerp(a.y, b.y, t);
    q.z=lerp(a.z, b.z, t);
    q.w=lerp(a.w, b.w, t);
    return qn(q);
}
static M4 qmat(Q q) {
    M4 m;
    float xx, yy, zz, xy, xz, yz, xw, yw, zw;
    q=qn(q);
    xx=q.x*q.x;
    yy=q.y*q.y;
    zz=q.z*q.z;
    xy=q.x*q.y;
    xz=q.x*q.z;
    yz=q.y*q.z;
    xw=q.x*q.w;
    yw=q.y*q.w;
    zw=q.z*q.w;
    mid(&m);
    m.m[0]=1.0f-2.0f*(yy+zz);
    m.m[1]=2.0f*(xy+zw);
    m.m[2]=2.0f*(xz-yw);
    m.m[4]=2.0f*(xy-zw);
    m.m[5]=1.0f-2.0f*(xx+zz);
    m.m[6]=2.0f*(yz+xw);
    m.m[8]=2.0f*(xz+yw);
    m.m[9]=2.0f*(yz-xw);
    m.m[10]=1.0f-2.0f*(xx+yy);
    return m;
}
static void world(Cmd* c, M4* out) {
    M4 s, t, r;
    Q q;
    mid(&s);
    mid(&t);
    s.m[0]=c->scl[0];
    s.m[5]=c->scl[1];
    s.m[10]=c->scl[2];
    t.m[12]=c->pos[0];
    t.m[13]=c->pos[1];
    t.m[14]=c->pos[2];
    q.x=c->q[0];
    q.y=c->q[1];
    q.z=c->q[2];
    q.w=c->q[3];
    r=qmat(q);
    *out=mmul(mmul(s, r), t);
}
static void viewproj(M4* out, float tsec) {
    float cp=cs(cam[4]), fwd[3]= {
        sn(cam[3])*cp, sn(cam[4]), cs(cam[3])*cp
    };
    float eye[3]= {
        cam[0], cam[1], cam[2]
    }, at[3]= {
        eye[0]+fwd[0], eye[1]+fwd[1], eye[2]+fwd[2]
    }, up[3]= {
        0, 1, 0
    };
    float z[3]= {
        eye[0]-at[0], eye[1]-at[1], eye[2]-at[2]
    };
    float iz=rsq(z[0]*z[0]+z[1]*z[1]+z[2]*z[2]);
    z[0]*=iz;
    z[1]*=iz;
    z[2]*=iz;
    float x[3]= {
        z[1]*up[2]-z[2]*up[1], z[2]*up[0]-z[0]*up[2], z[0]*up[1]-z[1]*up[0]
    };
    float ix=rsq(x[0]*x[0]+x[1]*x[1]+x[2]*x[2]);
    x[0]*=ix;
    x[1]*=ix;
    x[2]*=ix;
    float y[3]= {
        x[1]*z[2]-x[2]*z[1], x[2]*z[0]-x[0]*z[2], x[0]*z[1]-x[1]*z[0]
    };
    M4 v, p;
    mid(&v);
    zmem(&p, sizeof(p));
    v.m[0]=x[0];
    v.m[1]=y[0];
    v.m[2]=z[0];
    v.m[4]=x[1];
    v.m[5]=y[1];
    v.m[6]=z[1];
    v.m[8]=x[2];
    v.m[9]=y[2];
    v.m[10]=z[2];
    v.m[12]=-(x[0]*eye[0]+x[1]*eye[1]+x[2]*eye[2]);
    v.m[13]=-(y[0]*eye[0]+y[1]*eye[1]+y[2]*eye[2]);
    v.m[14]=-(z[0]*eye[0]+z[1]*eye[1]+z[2]*eye[2]);
    float f=cs(cam[5]*0.5f)/sn(cam[5]*0.5f);
    float asp=(float)W/(float)H;
    p.m[0]=f/asp;
    p.m[5]=f;
    p.m[10]=cam[7]/(cam[6]-cam[7]);
    p.m[11]=-1;
    p.m[14]=(cam[6]*cam[7])/(cam[6]-cam[7]);
    *out=mmul(v, p);
}
static int comps(int ty) {
    return (ty==1||ty==4)?1:(ty==2||ty==5)?2:(ty==3||ty==6)?3:(ty==7)?4:0;
}
static int isint(int ty) {
    return ty>=1&&ty<=3;
}
static void apply_track(Tr* r, float fr) {
    int a=-1, b=-1, i, n=r->count;
    Q qq;
    for(i=0;i<n;i++) {
        if((float)key[r->start+i].fr<=fr)a=i;
        if((float)key[r->start+i].fr>=fr) {
            b=i;
            break;
        }
    }
    if(a<0)a=b>=0?b:0;
    if(b<0)b=a;
    Key A=key[r->start+a], B=key[r->start+b], O=A;
    float tt=0;
    if(a!=b && !r->integral) {
        int span=B.fr-A.fr;
        tt=span>0?(fr-(float)A.fr)/(float)span:0;
        tt=cl(tt, 0, 1);
        if(r->kind==2) {
            for(i=0;i<3;i++)O.fv[i]=lerp(A.fv[i], B.fv[i], tt);
            qq=ql(qfa(A.fv+3), qfa(B.fv+3), tt);
            O.fv[3]=qq.x;
            O.fv[4]=qq.y;
            O.fv[5]=qq.z;
            O.fv[6]=qq.w;
            for(i=7;i<10;i++)O.fv[i]=lerp(A.fv[i], B.fv[i], tt);
        }
        else if(r->kind==4) {
            for(i=0;i<8;i++)O.fv[i]=(i==3)?lerpa(A.fv[i], B.fv[i], tt):lerp(A.fv[i], B.fv[i], tt);
        }
        else {
            int cnt=(r->kind==5)?10:comps(r->type);
            if(r->kind==1 && r->target>=0&&r->target<UVN && uv[r->target].src==3) {
                if(uv[r->target].type==7) {
                    qq=ql(qfa(A.fv), qfa(B.fv), tt);
                    O.fv[0]=qq.x;
                    O.fv[1]=qq.y;
                    O.fv[2]=qq.z;
                    O.fv[3]=qq.w;
                }
                else {
                    for(i=0;i<cnt;i++)O.fv[i]=lerp(A.fv[i], B.fv[i], tt);
                }
            }
            else for(i=0;i<cnt;i++)O.fv[i]=lerp(A.fv[i], B.fv[i], tt);
        }
    }
    if(r->kind==1 && r->target>=0&&r->target<UVN) {
        int c=comps(uv[r->target].type);
        for(i=0;i<c&&i<4;i++) {
            if(isint(uv[r->target].type))uv[r->target].iv[i]=O.iv[i];
            else uv[r->target].fv[i]=O.fv[i];
        }
        if(uv[r->target].src_cmd>=0&&uv[r->target].src_cmd<CMDN) {
            Cmd* cc=cmd+uv[r->target].src_cmd;
            if(uv[r->target].src==2)for(i=0;i<3;i++)cc->pos[i]=O.fv[i];
            else if(uv[r->target].src==3) {
                qq=uv[r->target].type==7?qfa(O.fv):qfe(O.fv);
                cc->q[0]=qq.x;
                cc->q[1]=qq.y;
                cc->q[2]=qq.z;
                cc->q[3]=qq.w;
            }
            else if(uv[r->target].src==4)for(i=0;i<3;i++)cc->scl[i]=O.fv[i];
        }
        else if(uv[r->target].src==6) {
            cam[3]=wrap(O.fv[0]);
            cam[4]=cl(O.fv[1], -1.50f, 1.50f);
        }
    }
    else if(r->kind==2 && r->target>=0&&r->target<CMDN) {
        Cmd* c=cmd+r->target;
        for(i=0;i<3;i++)c->pos[i]=O.fv[i];
        for(i=0;i<4;i++)c->q[i]=O.fv[3+i];
        for(i=0;i<3;i++)c->scl[i]=O.fv[7+i];
    }
    else if(r->kind==3 && r->target>=0&&r->target<CMDN) {
        cmd[r->target].enabled=O.iv[0]!=0;
    }
    else if(r->kind==4) {
        for(i=0;i<8;i++)cam[i]=O.fv[i];
        cam[3]=wrap(cam[3]);
        cam[4]=cl(cam[4], -1.50f, 1.50f);
    }
    else if(r->kind==5) {
        for(i=0;i<10;i++)dl[i]=O.fv[i];
    }
}
static void timeline(float sec) {
    if(!TL_ON||TL_LEN<1)return;
    float fr=sec*(float)TL_FPS;
    if(TL_LOOP)while(fr>=(float)TL_LEN)fr-=(float)TL_LEN;
    if(fr>(float)(TL_LEN-1))fr=(float)(TL_LEN-1);
    if(!TL_LERP)fr=(float)((int)fr);
    for(int i=0;i<TRN;i++)if(tr[i].enabled)apply_track(tr+i, fr);
}
static void fill_user(UserCB* u) {
    int i, j;
    zmem(u, sizeof(*u));
    for(i=0;i<UVN&&i<64;i++) {
        if(isint(uv[i].type)) cpy(u->slots[i], uv[i].iv, comps(uv[i].type)*4);
        else for(j=0;j<comps(uv[i].type);j++)u->slots[i][j]=uv[i].fv[j];
    }
}
static HRESULT compile(const char* src, unsigned int len, const char* e, const char* m, ID3DBlob** b) {
    ID3DBlob* er=0;
    HRESULT hr=D3DCompile(src, len, 0, 0, 0, e, m, D3DCOMPILE_OPTIMIZATION_LEVEL3, 0, b, &er);
    if(er)ID3D10Blob_Release(er);
    return hr;
}
static void init_shaders() {
    D3D11_INPUT_ELEMENT_DESC il[3];
    zmem(il, sizeof(il));
    il[0].SemanticName="POSITION";
    il[0].Format=DXGI_FORMAT_R32G32B32_FLOAT;
    il[0].AlignedByteOffset=0;
    il[0].InputSlotClass=D3D11_INPUT_PER_VERTEX_DATA;
    il[1].SemanticName="NORMAL";
    il[1].Format=DXGI_FORMAT_R32G32B32_FLOAT;
    il[1].AlignedByteOffset=12;
    il[1].InputSlotClass=D3D11_INPUT_PER_VERTEX_DATA;
    il[2].SemanticName="TEXCOORD";
    il[2].Format=DXGI_FORMAT_R32G32_FLOAT;
    il[2].AlignedByteOffset=24;
    il[2].InputSlotClass=D3D11_INPUT_PER_VERTEX_DATA;
    for(int i=0;i<SHN;i++) {
        ID3DBlob *vs=0, *ps=0;
        if(SUCCEEDED(compile(sh[i].src, sh[i].len, "VSMain", "vs_5_0", &vs))&&SUCCEEDED(compile(sh[i].src, sh[i].len, "PSMain", "ps_5_0", &ps))) {
            ID3D11Device_CreateVertexShader(dev, ID3D10Blob_GetBufferPointer(vs), ID3D10Blob_GetBufferSize(vs), 0, &sh[i].vs);
            ID3D11Device_CreatePixelShader(dev, ID3D10Blob_GetBufferPointer(ps), ID3D10Blob_GetBufferSize(ps), 0, &sh[i].ps);
            ID3D11Device_CreateInputLayout(dev, il, 3, ID3D10Blob_GetBufferPointer(vs), ID3D10Blob_GetBufferSize(vs), &sh[i].il);
        }
        if(vs)ID3D10Blob_Release(vs);
        if(ps)ID3D10Blob_Release(ps);
    }
}
static void mkbuf(int id, float* v, unsigned int bytes) {
    D3D11_BUFFER_DESC d;
    D3D11_SUBRESOURCE_DATA s;
    zmem(&d, sizeof(d));
    zmem(&s, sizeof(s));
    d.ByteWidth=bytes;
    d.BindFlags=D3D11_BIND_VERTEX_BUFFER;
    s.pSysMem=v;
    ID3D11Device_CreateBuffer(dev, &d, &s, &prim_vb[id]);
}
static void pv(float* v, int* n, float x, float y, float z, float nx, float ny, float nz, float u, float vv) {
    int i=*n;
    v[i+0]=x;
    v[i+1]=y;
    v[i+2]=z;
    v[i+3]=nx;
    v[i+4]=ny;
    v[i+5]=nz;
    v[i+6]=u;
    v[i+7]=vv;
    *n=i+8;
}
static void init_prims() {
    static float cube[]= {
        -1, -1, -1, 0, 0, -1, 0, 1, 1, 1, -1, 0, 0, -1, 1, 0, 1, -1, -1, 0, 0, -1, 1, 1, -1, -1, -1, 0, 0, -1, 0, 1, -1, 1, -1, 0, 0, -1, 0, 0, 1, 1, -1, 0, 0, -1, 1, 0, -1, -1, 1, 0, 0, 1, 0, 1, 1, -1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, -1, -1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, -1, 1, 1, 0, 0, 1, 0, 0, -1, -1, -1, -1, 0, 0, 0, 1, -1, -1, 1, -1, 0, 0, 1, 1, -1, 1, 1, -1, 0, 0, 1, 0, -1, -1, -1, -1, 0, 0, 0, 1, -1, 1, 1, -1, 0, 0, 1, 0, -1, 1, -1, -1, 0, 0, 0, 0, 1, -1, -1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, -1, 1, 1, 0, 0, 1, 1, 1, -1, -1, 1, 0, 0, 0, 1, 1, 1, -1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, -1, -1, -1, 0, -1, 0, 0, 1, 1, -1, -1, 0, -1, 0, 1, 1, 1, -1, 1, 0, -1, 0, 1, 0, -1, -1, -1, 0, -1, 0, 0, 1, 1, -1, 1, 0, -1, 0, 1, 0, -1, -1, 1, 0, -1, 0, 0, 0, -1, 1, -1, 0, 1, 0, 0, 1, -1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, -1, 1, -1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, -1, 0, 1, 0, 1, 1
    };
    static float quad[]= {
        -1, -1, 0, 0, 0, 1, 0, 1, 1, -1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, -1, -1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, -1, 1, 0, 0, 0, 1, 0, 0
    };
    static float tet[]= {
        1, 1, 1, 0.57735f, 0.57735f, 0.57735f, 0.5f, 0, -1, -1, 1, 0.57735f, 0.57735f, 0.57735f, 0, 1, -1, 1, -1, 0.57735f, 0.57735f, 0.57735f, 1, 1, 1, 1, 1, 0.57735f, -0.57735f, 0.57735f, 0.5f, 0, 1, -1, -1, 0.57735f, -0.57735f, 0.57735f, 0, 1, -1, -1, 1, 0.57735f, -0.57735f, 0.57735f, 1, 1, 1, 1, 1, 0.57735f, 0.57735f, -0.57735f, 0.5f, 0, -1, 1, -1, 0.57735f, 0.57735f, -0.57735f, 0, 1, 1, -1, -1, 0.57735f, 0.57735f, -0.57735f, 1, 1, -1, -1, 1, -0.57735f, -0.57735f, -0.57735f, 0.5f, 0, 1, -1, -1, -0.57735f, -0.57735f, -0.57735f, 0, 1, -1, 1, -1, -0.57735f, -0.57735f, -0.57735f, 1, 1
    };
    static float sph[2880*8];
    int n=0;
    for(int r=0;r<16;r++) {
        for(int s=0;s<32;s++) {
            float v0=(float)r/16.0f, v1=(float)(r+1)/16.0f, u0=(float)s/32.0f, u1=(float)(s+1)/32.0f;
            float th0=v0*LT_PI, th1=v1*LT_PI, ph0=u0*6.28318530718f, ph1=u1*6.28318530718f;
            float sr0=sn(th0), sr1=sn(th1);
            float p0[8]= {
                sr0*cs(ph0), cs(th0), sr0*sn(ph0), sr0*cs(ph0), cs(th0), sr0*sn(ph0), u0, v0
            };
            float p1[8]= {
                sr1*cs(ph0), cs(th1), sr1*sn(ph0), sr1*cs(ph0), cs(th1), sr1*sn(ph0), u0, v1
            };
            float p2[8]= {
                sr0*cs(ph1), cs(th0), sr0*sn(ph1), sr0*cs(ph1), cs(th0), sr0*sn(ph1), u1, v0
            };
            float p3[8]= {
                sr1*cs(ph1), cs(th1), sr1*sn(ph1), sr1*cs(ph1), cs(th1), sr1*sn(ph1), u1, v1
            };
            if(r==0) {
                pv(sph, &n, p0[0], p0[1], p0[2], p0[3], p0[4], p0[5], p0[6], p0[7]);
                pv(sph, &n, p1[0], p1[1], p1[2], p1[3], p1[4], p1[5], p1[6], p1[7]);
                pv(sph, &n, p3[0], p3[1], p3[2], p3[3], p3[4], p3[5], p3[6], p3[7]);
            }
            else if(r==15) {
                pv(sph, &n, p0[0], p0[1], p0[2], p0[3], p0[4], p0[5], p0[6], p0[7]);
                pv(sph, &n, p1[0], p1[1], p1[2], p1[3], p1[4], p1[5], p1[6], p1[7]);
                pv(sph, &n, p2[0], p2[1], p2[2], p2[3], p2[4], p2[5], p2[6], p2[7]);
            }
            else {
                pv(sph, &n, p0[0], p0[1], p0[2], p0[3], p0[4], p0[5], p0[6], p0[7]);
                pv(sph, &n, p1[0], p1[1], p1[2], p1[3], p1[4], p1[5], p1[6], p1[7]);
                pv(sph, &n, p2[0], p2[1], p2[2], p2[3], p2[4], p2[5], p2[6], p2[7]);
                pv(sph, &n, p2[0], p2[1], p2[2], p2[3], p2[4], p2[5], p2[6], p2[7]);
                pv(sph, &n, p1[0], p1[1], p1[2], p1[3], p1[4], p1[5], p1[6], p1[7]);
                pv(sph, &n, p3[0], p3[1], p3[2], p3[3], p3[4], p3[5], p3[6], p3[7]);
            }
        }
    }
    mkbuf(1, cube, sizeof(cube));
    mkbuf(2, quad, sizeof(quad));
    mkbuf(3, tet, sizeof(tet));
    mkbuf(4, sph, (unsigned int)(n*4));
}
static void cb_make(ID3D11Buffer** b, unsigned int sz) {
    D3D11_BUFFER_DESC d;
    zmem(&d, sizeof(d));
    d.ByteWidth=(sz+15)&~15;
    d.Usage=D3D11_USAGE_DYNAMIC;
    d.BindFlags=D3D11_BIND_CONSTANT_BUFFER;
    d.CPUAccessFlags=D3D11_CPU_ACCESS_WRITE;
    ID3D11Device_CreateBuffer(dev, &d, 0, b);
}
static void cb_up(ID3D11Buffer* b, void* data, unsigned int sz) {
    D3D11_MAPPED_SUBRESOURCE m;
    if(SUCCEEDED(ID3D11DeviceContext_Map(ctx, (ID3D11Resource*)b, 0, D3D11_MAP_WRITE_DISCARD, 0, &m))) {
        cpy(m.pData, data, sz);
        ID3D11DeviceContext_Unmap(ctx, (ID3D11Resource*)b, 0);
    }
}
static void render(float sec) {
    timeline(sec);
    float clr[4]= {
        0, 0, 0, 1
    };
    ID3D11DeviceContext_OMSetRenderTargets(ctx, 1, &rtv, dsv);
    SceneCB sc;
    UserCB uc;
    ObjectCB oc;
    M4 vp;
    zmem(&sc, sizeof(sc));
    viewproj(&vp, sec);
    cpy(sc.view_proj, vp.m, 64);
    cpy(sc.prev_view_proj, vp.m, 64);
    sc.time_vec[0]=sec;
    sc.time_vec[2]=sec*60.0f;
    sc.cam_pos[0]=cam[0];
    sc.cam_pos[1]=cam[1];
    sc.cam_pos[2]=cam[2];
    float cp=cs(cam[4]);
    sc.cam_dir[0]=sn(cam[3])*cp;
    sc.cam_dir[1]=sn(cam[4]);
    sc.cam_dir[2]=cs(cam[3])*cp;
    float ldx=dl[3]-dl[0], ldy=dl[4]-dl[1], ldz=dl[5]-dl[2], li=rsq(ldx*ldx+ldy*ldy+ldz*ldz);
    sc.light_dir[0]=ldx*li;
    sc.light_dir[1]=ldy*li;
    sc.light_dir[2]=ldz*li;
    sc.light_dir[3]=dl[9];
    sc.light_color[0]=dl[6];
    sc.light_color[1]=dl[7];
    sc.light_color[2]=dl[8];
    cb_up(scene_cb, &sc, sizeof(sc));
    fill_user(&uc);
    cb_up(user_cb, &uc, sizeof(uc));
    ID3D11DeviceContext_ClearRenderTargetView(ctx, rtv, clr);
    if(dsv)ID3D11DeviceContext_ClearDepthStencilView(ctx, dsv, D3D11_CLEAR_DEPTH, 1, 0);
    for(int i=0;i<CMDN;i++) {
        Cmd* c=cmd+i;
        if(!c->enabled)continue;
        if(c->type==1) {
            if(c->ccen)ID3D11DeviceContext_ClearRenderTargetView(ctx, rtv, c->cc);
            if(c->cden&&dsv)ID3D11DeviceContext_ClearDepthStencilView(ctx, dsv, D3D11_CLEAR_DEPTH, c->dc, 0);
        }
        else if(c->type==2 && c->shader>=0&&c->shader<SHN&&sh[c->shader].vs&&sh[c->shader].ps) {
            M4 w;
            world(c, &w);
            cpy(oc.world, w.m, 64);
            cb_up(object_cb, &oc, sizeof(oc));
            ID3D11DeviceContext_VSSetConstantBuffers(ctx, 0, 1, &scene_cb);
            ID3D11DeviceContext_PSSetConstantBuffers(ctx, 0, 1, &scene_cb);
            ID3D11DeviceContext_VSSetConstantBuffers(ctx, 1, 1, &object_cb);
            ID3D11DeviceContext_PSSetConstantBuffers(ctx, 1, 1, &object_cb);
            ID3D11DeviceContext_VSSetConstantBuffers(ctx, 2, 1, &user_cb);
            ID3D11DeviceContext_PSSetConstantBuffers(ctx, 2, 1, &user_cb);
            if(c->mk>0&&c->mk<5&&prim_vb[c->mk]) {
                unsigned int st=32, off=0;
                ID3D11DeviceContext_IASetInputLayout(ctx, sh[c->shader].il);
                ID3D11DeviceContext_IASetVertexBuffers(ctx, 0, 1, &prim_vb[c->mk], &st, &off);
            }
            else {
                ID3D11DeviceContext_IASetInputLayout(ctx, 0);
                ID3D11DeviceContext_IASetVertexBuffers(ctx, 0, 0, 0, 0, 0);
            }
            ID3D11DeviceContext_IASetIndexBuffer(ctx, 0, DXGI_FORMAT_R32_UINT, 0);
            ID3D11DeviceContext_IASetPrimitiveTopology(ctx, c->topology?D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST:D3D11_PRIMITIVE_TOPOLOGY_POINTLIST);
            ID3D11DeviceContext_VSSetShader(ctx, sh[c->shader].vs, 0, 0);
            ID3D11DeviceContext_PSSetShader(ctx, sh[c->shader].ps, 0, 0);
            ID3D11DeviceContext_DrawInstanced(ctx, c->vc, c->ic, 0, 0);
        }
    }
    IDXGISwapChain_Present(swp, 1, 0);
}
static LRESULT CALLBACK wp(HWND h, UINT m, WPARAM w, LPARAM l) {
    if(m==WM_KEYDOWN&&w==VK_ESCAPE)PostQuitMessage(0);
    if(m==WM_CLOSE||m==WM_DESTROY) {
        PostQuitMessage(0);
        return 0;
    }
    return DefWindowProcA(h, m, w, l);
}
void WINAPI WinMainCRTStartup(void) {
    WNDCLASSA wc;
    zmem(&wc, sizeof(wc));
    wc.lpfnWndProc=wp;
    wc.hInstance=GetModuleHandleA(0);
    wc.lpszClassName=LT_WNDCLS;
    RegisterClassA(&wc);
    W=GetSystemMetrics(SM_CXSCREEN);
    H=GetSystemMetrics(SM_CYSCREEN);
    HWND hw=CreateWindowExA(0, LT_WNDCLS, "lt64k", WS_POPUP|WS_VISIBLE, 0, 0, W, H, 0, 0, wc.hInstance, 0);
    ShowCursor(FALSE);
    DXGI_SWAP_CHAIN_DESC sd;
    zmem(&sd, sizeof(sd));
    sd.BufferCount=1;
    sd.BufferDesc.Width=W;
    sd.BufferDesc.Height=H;
    sd.BufferDesc.Format=DXGI_FORMAT_R8G8B8A8_UNORM;
    sd.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;
    sd.OutputWindow=hw;
    sd.SampleDesc.Count=1;
    sd.Windowed=TRUE;
    if(FAILED(D3D11CreateDeviceAndSwapChain(0, D3D_DRIVER_TYPE_HARDWARE, 0, 0, 0, 0, D3D11_SDK_VERSION, &sd, &swp, &dev, 0, &ctx)))ExitProcess(1);
    ID3D11Texture2D* bb=0;
    IDXGISwapChain_GetBuffer(swp, 0, &IID_ID3D11Texture2D, (void**)&bb);
    ID3D11Device_CreateRenderTargetView(dev, (ID3D11Resource*)bb, 0, &rtv);
    ID3D11Texture2D_Release(bb);
    D3D11_TEXTURE2D_DESC dd;
    zmem(&dd, sizeof(dd));
    dd.Width=W;
    dd.Height=H;
    dd.MipLevels=1;
    dd.ArraySize=1;
    dd.Format=DXGI_FORMAT_D24_UNORM_S8_UINT;
    dd.SampleDesc.Count=1;
    dd.BindFlags=D3D11_BIND_DEPTH_STENCIL;
    ID3D11Texture2D* dt=0;
    if(SUCCEEDED(ID3D11Device_CreateTexture2D(dev, &dd, 0, &dt))) {
        ID3D11Device_CreateDepthStencilView(dev, (ID3D11Resource*)dt, 0, &dsv);
        ID3D11Texture2D_Release(dt);
    }
    D3D11_VIEWPORT vp;
    zmem(&vp, sizeof(vp));
    vp.Width=(float)W;
    vp.Height=(float)H;
    vp.MinDepth=0;
    vp.MaxDepth=1;
    ID3D11DeviceContext_RSSetViewports(ctx, 1, &vp);
    cb_make(&scene_cb, sizeof(SceneCB));
    cb_make(&object_cb, sizeof(ObjectCB));
    cb_make(&user_cb, sizeof(UserCB));
    init_shaders();
    init_prims();
    DWORD t0=GetTickCount();
    MSG msg;
    for(;;) {
        while(PeekMessageA(&msg, 0, 0, 0, PM_REMOVE)) {
            if(msg.message==WM_QUIT)ExitProcess(0);
            TranslateMessage(&msg);
            DispatchMessageA(&msg);
        }
        render((float)(GetTickCount()-t0)*0.001f);
    }
}

