// generated by lazyTool build64k.cpp from ..\bin\projects\colorgrad.lt
//
// This file is a procedural-only standalone player. It contains no model files,
// no texture files and no editor UI. Geometry is either produced by the shader
// from SV_VertexID or by the tiny built-in primitive vertex buffers below.
// Shadows, render targets, command parameters and timeline animation are kept.
#define WIN32_LEAN_AND_MEAN
#define COBJMACROS
#include <windows.h>
#include <stddef.h>
#include <d3d11.h>
#include <d3dcompiler.h>
#define LT_WNDCLS "lt64k_window"
#define LT_PI 3.14159265358979323846f
// -----------------------------------------------------------------------------
// Build-time options. This generated player assumes fullscreen borderless mode.
// W/H and RW/RH are always the fullscreen monitor/backbuffer size. That keeps
// the projection aspect, scene depth, scene-scaled render targets, and final
// output in the same resolution space. Fixed custom RTs still keep the size
// authored in the .lt file when scene_scale_divisor == 0.
//
// Useful overrides through LT64K_CFLAGS:
//   /DLT_VSYNC=1                        Present with VSync for smoother pacing.
//   /DLT_DEBUG_FPS=1                    Compile the tiny GDI FPS overlay.
// -----------------------------------------------------------------------------
#define LT_PROJECT_W 1280
#define LT_PROJECT_H 720
#define LT_SHADOW_W 1024
#define LT_SHADOW_H 1204
#ifndef LT_VSYNC
#define LT_VSYNC 0
#endif
#ifndef LT_DEBUG_FPS
#define LT_DEBUG_FPS 0
#endif
// Minimal CRT replacements and tiny math types. /NODEFAULTLIB builds need these.
int _fltused=0;
typedef unsigned int u32;
typedef struct {
    float m[16];
} M4;
void* __cdecl memset(void* d, int c, size_t n) {
    unsigned char* p=(unsigned char*)d;
    while(n--)*p++=(unsigned char)c;
    return d;
}
void* __cdecl memcpy(void* d, const void* s, size_t n) {
    unsigned char* p=(unsigned char*)d;
    const unsigned char* q=(const unsigned char*)s;
    while(n--)*p++=*q++;
    return d;
}
// Constant buffers shared with the HLSL files. Keep layout in sync with shaders.
typedef struct {
    float view_proj[16];
    float time_vec[4];
    float light_dir[4];
    float light_color[4];
    float cam_pos[4];
    float shadow_view_proj[16];
    float inv_view_proj[16];
    float prev_view_proj[16];
    float prev_inv_view_proj[16];
    float prev_shadow_view_proj[16];
    float cam_dir[4];
    float shadow_cascade_splits[4];
    float shadow_params[4];
    float shadow_cascade_rects[4][4];
    float shadow_cascade_view_proj[4][16];
} SceneCB;
typedef union {
    float f[64][4];
    int i[64][4];
} UserCB;
typedef struct {
    float world[16];
} ObjectCB;
// Global D3D handles and runtime sizes. This player is fullscreen-only, so
// W/H are the monitor/backbuffer size and RW/RH intentionally equal W/H.
// Camera projection, scene depth and scene-scaled render textures all use
// this fullscreen size. Only fixed custom RTs keep their authored dimensions.
static ID3D11Device* dev;
static ID3D11DeviceContext* ctx;
static IDXGISwapChain* swp;
static ID3D11RenderTargetView* rtv;
static ID3D11Texture2D* depth_tex;
static ID3D11DepthStencilView* dsv;
static ID3D11ShaderResourceView* depth_srv;
static ID3D11Texture2D* shadow_tex;
static ID3D11DepthStencilView* shadow_dsv;
static ID3D11ShaderResourceView* shadow_srv;
static ID3D11SamplerState* smp_lin;
static ID3D11SamplerState* smp_cmp;
static ID3D11DepthStencilState* ds[4];
static ID3D11RasterizerState* rs[2];
static ID3D11BlendState* bs[4];
static ID3D11Buffer* scene_cb;
static ID3D11Buffer* object_cb;
static ID3D11Buffer* user_cb;
static ID3D11Buffer* prim_vb[6];
static HWND wh;
static int W, H, RW, RH, dbg_on=LT_DEBUG_FPS;
typedef struct {
    const char* src;
    unsigned int len;
    ID3D11VertexShader* vs;
    ID3D11PixelShader* ps;
    ID3D11InputLayout* il;
} Sh;
typedef struct {
    int w, h, fmt, rtv, srv, uav, dsv, div;
} Rtd;
// Embedded shader source. It is compiled at startup so the player does not
// need precompiled bytecode or any external shader files.
static const char sh_src_0[] =
"// Minimal example shader used by the default scene. It now samples the shared\n"
"// shadow atlas and uses the cascade data exposed through SceneCB.\n"
"cbuffer SceneCB : register(b0)\n"
"{\n"
"    float4x4 ViewProj;\n"
"    float4 TimeVec;\n"
"    float4 LightDir;\n"
"    float4 LightColor;\n"
"    float4 CamPos;\n"
"    float4x4 ShadowViewProj;\n"
"    float4x4 InvViewProj;\n"
"    float4x4 PrevViewProj;\n"
"    float4x4 PrevInvViewProj;\n"
"    float4x4 PrevShadowViewProj;\n"
"    float4 CamDir;\n"
"    float4 ShadowCascadeSplits;\n"
"    float4 ShadowParams;\n"
"    float4 ShadowCascadeRects[4];\n"
"    float4x4 ShadowCascadeViewProj[4];\n"
"};\n"
"\n"
"cbuffer ObjectCB : register(b1)\n"
"{\n"
"    float4x4 World;\n"
"};\n"
"\n"
"Texture2D ShadowMap : register(t7);\n"
"SamplerComparisonState ShadowSampler : register(s1);\n"
"\n"
"struct VSIn {\n"
"    float3 pos : POSITION;\n"
"    float3 nor : NORMAL;\n"
"    float2 uv  : TEXCOORD0;\n"
"};\n"
"\n"
"struct VSOut {\n"
"    float4 pos  : SV_POSITION;\n"
"    float3 nor  : NORMAL;\n"
"    float3 wpos : TEXCOORD0;\n"
"};\n"
"\n"
"VSOut VSMain(VSIn v) {\n"
"    VSOut o;\n"
"    float4 wpos = mul(World, float4(v.pos, 1.0));\n"
"    o.pos = mul(ViewProj, wpos);\n"
"    o.wpos = wpos.xyz;\n"
"    o.nor = normalize(mul(World, float4(v.nor, 0.0)).xyz);\n"
"    return o;\n"
"}\n"
"\n"
"float sample_shadow_cascade(int cascade_index, float3 wpos, float ndl) {\n"
"    uint shadow_w = 0;\n"
"    uint shadow_h = 0;\n"
"    ShadowMap.GetDimensions(shadow_w, shadow_h);\n"
"    if (shadow_w == 0 || shadow_h == 0)\n"
"        return 1.0;\n"
"\n"
"    float4 shadow_clip = mul(ShadowCascadeViewProj[cascade_index], float4(wpos, 1.0));\n"
"    if (abs(shadow_clip.w) < 1e-5)\n"
"        return 1.0;\n"
"\n"
"    float3 shadow_ndc = shadow_clip.xyz / shadow_clip.w;\n"
"    float2 uv_local = float2(shadow_ndc.x * 0.5 + 0.5, shadow_ndc.y * -0.5 + 0.5);\n"
"    if (uv_local.x < 0.0 || uv_local.x > 1.0 || uv_local.y < 0.0 || uv_local.y > 1.0)\n"
"        return 1.0;\n"
"    if (shadow_ndc.z < 0.0 || shadow_ndc.z > 1.0)\n"
"        return 1.0;\n"
"\n"
"    float4 rect = ShadowCascadeRects[cascade_index];\n"
"    float2 atlas_uv = uv_local * rect.xy + rect.zw;\n"
"    float bias = lerp(0.0025, 0.0003, saturate(ndl));\n"
"    return ShadowMap.SampleCmpLevelZero(ShadowSampler, atlas_uv, shadow_ndc.z - bias);\n"
"}\n"
"\n"
"int select_shadow_cascade(float3 wpos) {\n"
"    int cascade_count = clamp((int)ShadowParams.x, 1, 4);\n"
"    float view_depth = dot(wpos - CamPos.xyz, CamDir.xyz);\n"
"    int cascade_index = 0;\n"
"    [unroll]\n"
"    for (int i = 0; i < 3; i++) {\n"
"        if (i + 1 < cascade_count && view_depth > ShadowCascadeSplits[i])\n"
"            cascade_index = i + 1;\n"
"    }\n"
"    return cascade_index;\n"
"}\n"
"\n"
"float4 PSMain(VSOut i) : SV_Target {\n"
"    float3 n = normalize(i.nor);\n"
"    float3 ld = normalize(-LightDir.xyz);\n"
"    float ndl = saturate(dot(n, ld));\n"
"    int cascade_index = select_shadow_cascade(i.wpos);\n"
"    float shadow = sample_shadow_cascade(cascade_index, i.wpos, ndl);\n"
"\n"
"    float3 base = 0.30 + 0.70 * (0.5 + 0.5 * n);\n"
"    float3 sun = LightColor.xyz * LightDir.w * ndl * shadow;\n"
"    float3 ambient = float3(0.06, 0.065, 0.08);\n"
"    return float4(base * (ambient + sun), 1.0);\n"
"}\n"
"";
static Sh sh[1] = {
    {
        sh_src_0, sizeof(sh_src_0)-1, 0, 0, 0
    },
};
// Render texture descriptors copied from the project. Width/height 0 means
// use the internal render size RW/RH; div is used by half/quarter-resolution passes.
static Rtd rtd[1] = {
    {
        1, 1, 28, 0, 0, 0, 0, 0
    },
};
static ID3D11Texture2D* rt_tex[1];
static ID3D11RenderTargetView* rt_rtv[1];
static ID3D11ShaderResourceView* rt_srv[1];
// Flattened render commands. Resource names are gone here; everything is a
// small integer code so the runtime can be straightforward and deterministic.
typedef struct {
    int type, enabled, shader, shs, topology, mk, vc, ic, ccen, cden, ccs, dcs, rt, dep, dt, dw, ab, cb, cw, scast, srecv, pst, pc, tc, sc;
    int tex[8], tsl[8], srv[8], ssl[8];
    float cc[4], dc, pos[3], q[4], scl[3];
} Cmd;
static Cmd cmd[1] = {
    {
        1, 1, -1, -1, 1, 0, 3, 1, 1, 1, 0, -1, -2, -2, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, {
            -1, -1, -1, -1, -1, -1, -1, -1
        }, {
            0, 0, 0, 0, 0, 0, 0, 0
        }, {
            -1, -1, -1, -1, -1, -1, -1, -1
        }, {
            0, 0, 0, 0, 0, 0, 0, 0
        }, {
            0.432732642f, 0.0f, 0.674210966f, 1.0f
        }, 1.0f, {
            0.0f, 0.0f, 0.0f
        }, {
            0.0f, 0.0f, 0.0f, 1.0f
        }, {
            1.0f, 1.0f, 1.0f
        }
    },
};
typedef struct {
    int type, enabled;
    int iv[4];
    float fv[4];
} Par;
static Par par[1] = {
    {
        0, 0, {
            0, 0, 0, 0
        }, {
            0.0f, 0.0f, 0.0f, 0.0f
        }
    },
};
typedef struct {
    int type, src, src_cmd;
    int iv[4];
    float fv[4];
} Uv;
static Uv uv[1] = {
    {
        7, 1, -1, {
            0, 0, 0, 0
        }, {
            0.432732642f, 0.0f, 0.674210966f, 1.0f
        }
    },
};
// Timeline data. Frames are separate from values, and values are split into
// int and float streams so a float track does not carry unused int/quaternion data.
typedef struct {
    int kind, target, type, integral, fs, ds, count, comp, enabled;
} Tr;
static int kfr[2]= {
    0, 9
};
static int ki[1]= {
    0
};
static float kf[8]= {
    1.0f, 0.0f, 0.0f, 1.0f, 0.158620358f, 0.0f, 1.0f, 1.0f
};
static Tr tr[1] = {
    {
        1, 0, 7, 0, 0, 0, 2, 4, 1
    },
};
static float cam0[8]= {
    5.0f, 5.0f, 5.0f, -2.3561945f, -0.615479767f, 1.04700005f, 0.00100000005f, 100.0f
};
static float dl0[39]= {
    5.0f, 5.0f, 5.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.949999988f, 0.899999976f, 1.0f, 1024.0f, 1204.0f, 0.00999999978f, 10.0f, 8.0f, 8.0f, 1.0f, 5.0f, 0.649999976f, 0.443228424f, 8.0f, 8.0f, 0.00999999978f, 10.0f, 0.921136975f, 8.0f, 8.0f, 0.00999999978f, 10.0f, 1.69907975f, 8.0f, 8.0f, 0.00999999978f, 10.0f, 5.0f, 8.0f, 8.0f, 0.00999999978f, 10.0f
};
static float cam[8], dl[39];
enum {
    CMDN=1, SHN=1, RTN=0, UVN=1, PN=0, TRN=1, KEYN=2, TL_FPS=5, TL_LEN=10, TL_LOOP=1, TL_ON=1, TL_LERP=1
};
// -----------------------------------------------------------------------------
// Runtime helpers
// -----------------------------------------------------------------------------
// The generated runtime is kept as plain C. It avoids the CRT where practical,
// but it is not source-golfed: comments document the moving parts so the player
// can be extended later.
static void zmem(void* p, int n) {
    unsigned char* b=(unsigned char*)p;
    while(n--)*b++=0;
}
static void cpy(void* d, const void* s, int n) {
    unsigned char* a=(unsigned char*)d;
    const unsigned char* b=(const unsigned char*)s;
    while(n--)*a++=*b++;
}
static float ab(float x) {
    return x<0?-x:x;
}
static float cl(float x, float a, float b) {
    return x<a?a:(x>b?b:x);
}
static float wrap(float x) {
    while(x>LT_PI)x-=6.28318530718f;
    while(x<-LT_PI)x+=6.28318530718f;
    return x;
}
static float sn(float x) {
    int neg=0;
    x=wrap(x);
    if(x<0) {
        neg=1;
        x=-x;
    }
    if(x>1.57079632679f)x=3.14159265359f-x;
    float x2=x*x;
    float r=x*(1.0f-x2*(0.1666666667f-x2*(0.00833333333f-x2*(0.000198412698f-x2*(0.00000275573192f-x2*0.0000000250521084f)))));
    return neg?-r:r;
}
static float cs(float x) {
    return sn(x+1.57079632679f);
}
static float lerp(float a, float b, float t) {
    return a+(b-a)*t;
}
static float lerpa(float a, float b, float t) {
    float d=wrap(b-a);
    return wrap(a+d*t);
}
static float rsq(float x) {
    union {
        float f;
        unsigned int i;
    }
    u;
    float xh=x*0.5f;
    if(x<=0) return 0;
    u.f=x;
    u.i=0x5f3759df-(u.i>>1);
    u.f=u.f*(1.5f-xh*u.f*u.f);
    u.f=u.f*(1.5f-xh*u.f*u.f);
    return u.f;
}
static float sqt(float x) {
    return x<=0?0:x*rsq(x);
}
typedef struct {
    float x, y, z, w;
} Q;
static void mid(M4* m) {
    zmem(m, sizeof(M4));
    m->m[0]=m->m[5]=m->m[10]=m->m[15]=1;
}
static M4 mmul(M4 a, M4 b) {
    M4 r;
    int row, col, k;
    zmem(&r, sizeof(r));
    for(row=0;row<4;row++)for(col=0;col<4;col++)for(k=0;k<4;k++)r.m[row*4+col]+=a.m[row*4+k]*b.m[k*4+col];
    return r;
}
static void rotxyz(float* rr, M4* out) {
    float cx=cs(rr[0]), sx=sn(rr[0]), cy=cs(rr[1]), sy=sn(rr[1]), cz=cs(rr[2]), sz=sn(rr[2]);
    M4 rx, ry, rz;
    mid(&rx);
    mid(&ry);
    mid(&rz);
    rx.m[5]=cx;
    rx.m[6]=sx;
    rx.m[9]=-sx;
    rx.m[10]=cx;
    ry.m[0]=cy;
    ry.m[2]=-sy;
    ry.m[8]=sy;
    ry.m[10]=cy;
    rz.m[0]=cz;
    rz.m[1]=sz;
    rz.m[4]=-sz;
    rz.m[5]=cz;
    *out=mmul(mmul(rx, ry), rz);
}
static Q qn(Q q) {
    float l=q.x*q.x+q.y*q.y+q.z*q.z+q.w*q.w;
    if(l<0.00000001f) {
        q.x=q.y=q.z=0;
        q.w=1;
        return q;
    }
    float r=rsq(l);
    q.x*=r;
    q.y*=r;
    q.z*=r;
    q.w*=r;
    return q;
}
static Q qfm(M4* m) {
    Q q;
    float m00=m->m[0], m01=m->m[1], m02=m->m[2], m10=m->m[4], m11=m->m[5], m12=m->m[6], m20=m->m[8], m21=m->m[9], m22=m->m[10], tr=m00+m11+m22, s;
    q.x=q.y=q.z=0;
    q.w=1;
    if(tr>0) {
        s=sqt(tr+1.0f)*2.0f;
        q.w=0.25f*s;
        q.x=(m12-m21)/s;
        q.y=(m20-m02)/s;
        q.z=(m01-m10)/s;
    }
    else if(m00>m11&&m00>m22) {
        s=sqt(1.0f+m00-m11-m22)*2.0f;
        q.w=(m12-m21)/s;
        q.x=0.25f*s;
        q.y=(m01+m10)/s;
        q.z=(m20+m02)/s;
    }
    else if(m11>m22) {
        s=sqt(1.0f+m11-m00-m22)*2.0f;
        q.w=(m20-m02)/s;
        q.x=(m01+m10)/s;
        q.y=0.25f*s;
        q.z=(m12+m21)/s;
    }
    else {
        s=sqt(1.0f+m22-m00-m11)*2.0f;
        q.w=(m01-m10)/s;
        q.x=(m20+m02)/s;
        q.y=(m12+m21)/s;
        q.z=0.25f*s;
    }
    return qn(q);
}
static Q qfe(float* r) {
    M4 m;
    rotxyz(r, &m);
    return qfm(&m);
}
static Q qfa(float* r) {
    Q q;
    q.x=r[0];
    q.y=r[1];
    q.z=r[2];
    q.w=r[3];
    return qn(q);
}
static Q ql(Q a, Q b, float t) {
    Q q;
    float d;
    a=qn(a);
    b=qn(b);
    d=a.x*b.x+a.y*b.y+a.z*b.z+a.w*b.w;
    if(d<0) {
        b.x=-b.x;
        b.y=-b.y;
        b.z=-b.z;
        b.w=-b.w;
    }
    q.x=lerp(a.x, b.x, t);
    q.y=lerp(a.y, b.y, t);
    q.z=lerp(a.z, b.z, t);
    q.w=lerp(a.w, b.w, t);
    return qn(q);
}
static M4 qmat(Q q) {
    M4 m;
    float xx, yy, zz, xy, xz, yz, xw, yw, zw;
    q=qn(q);
    xx=q.x*q.x;
    yy=q.y*q.y;
    zz=q.z*q.z;
    xy=q.x*q.y;
    xz=q.x*q.z;
    yz=q.y*q.z;
    xw=q.x*q.w;
    yw=q.y*q.w;
    zw=q.z*q.w;
    mid(&m);
    m.m[0]=1.0f-2.0f*(yy+zz);
    m.m[1]=2.0f*(xy+zw);
    m.m[2]=2.0f*(xz-yw);
    m.m[4]=2.0f*(xy-zw);
    m.m[5]=1.0f-2.0f*(xx+zz);
    m.m[6]=2.0f*(yz+xw);
    m.m[8]=2.0f*(xz+yw);
    m.m[9]=2.0f*(yz-xw);
    m.m[10]=1.0f-2.0f*(xx+yy);
    return m;
}
static void world(Cmd* c, M4* out) {
    M4 s, t, r;
    Q q;
    mid(&s);
    mid(&t);
    s.m[0]=c->scl[0];
    s.m[5]=c->scl[1];
    s.m[10]=c->scl[2];
    t.m[12]=c->pos[0];
    t.m[13]=c->pos[1];
    t.m[14]=c->pos[2];
    q.x=c->q[0];
    q.y=c->q[1];
    q.z=c->q[2];
    q.w=c->q[3];
    r=qmat(q);
    *out=mmul(mmul(s, r), t);
}
static void lookat(M4* r, float* eye, float* at, float* up) {
    float z[3]= {
        eye[0]-at[0], eye[1]-at[1], eye[2]-at[2]
    };
    float iz=rsq(z[0]*z[0]+z[1]*z[1]+z[2]*z[2]);
    z[0]*=iz;
    z[1]*=iz;
    z[2]*=iz;
    float x[3]= {
        z[1]*up[2]-z[2]*up[1], z[2]*up[0]-z[0]*up[2], z[0]*up[1]-z[1]*up[0]
    };
    float ix=rsq(x[0]*x[0]+x[1]*x[1]+x[2]*x[2]);
    if(ix==0) {
        x[0]=1;
        x[1]=x[2]=0;
    }
    else {
        x[0]*=ix;
        x[1]*=ix;
        x[2]*=ix;
    }
    float y[3]= {
        x[1]*z[2]-x[2]*z[1], x[2]*z[0]-x[0]*z[2], x[0]*z[1]-x[1]*z[0]
    };
    mid(r);
    r->m[0]=x[0];
    r->m[1]=y[0];
    r->m[2]=z[0];
    r->m[4]=x[1];
    r->m[5]=y[1];
    r->m[6]=z[1];
    r->m[8]=x[2];
    r->m[9]=y[2];
    r->m[10]=z[2];
    r->m[12]=-(x[0]*eye[0]+x[1]*eye[1]+x[2]*eye[2]);
    r->m[13]=-(y[0]*eye[0]+y[1]*eye[1]+y[2]*eye[2]);
    r->m[14]=-(z[0]*eye[0]+z[1]*eye[1]+z[2]*eye[2]);
}
static void persp(M4* p) {
    zmem(p, sizeof(M4));
    float f=cs(cam[5]*0.5f)/sn(cam[5]*0.5f), asp=(float)RW/(float)RH;
    p->m[0]=f/asp;
    p->m[5]=f;
    p->m[10]=cam[7]/(cam[6]-cam[7]);
    p->m[11]=-1;
    p->m[14]=(cam[6]*cam[7])/(cam[6]-cam[7]);
}
static void ortho(M4* p, float w, float h, float n, float fa) {
    if(w<0.01f)w=0.01f;
    if(h<0.01f)h=0.01f;
    if(n<0.0001f)n=0.0001f;
    if(fa<=n+0.001f)fa=n+0.001f;
    zmem(p, sizeof(M4));
    p->m[0]=2.0f/w;
    p->m[5]=2.0f/h;
    p->m[10]=1.0f/(n-fa);
    p->m[14]=n/(n-fa);
    p->m[15]=1.0f;
}
static void viewproj(M4* out, float tsec) {
    float cp=cs(cam[4]), fwd[3]= {
        sn(cam[3])*cp, sn(cam[4]), cs(cam[3])*cp
    };
    float eye[3]= {
        cam[0], cam[1], cam[2]
    }, at[3]= {
        eye[0]+fwd[0], eye[1]+fwd[1], eye[2]+fwd[2]
    }, up[3]= {
        0, 1, 0
    };
    M4 v, p;
    lookat(&v, eye, at, up);
    persp(&p);
    *out=mmul(v, p);
}
static void atlas(int ci, int cc, float* r) {
    if(cc<=1) {
        r[0]=r[1]=1;
        r[2]=r[3]=0;
        return;
    }
    if(ci<0)ci=0;
    if(ci>3)ci=3;
    float x=0, y=0, w=1, h=1;
    for(int i=0;i<=ci;i++) {
        if((i&1)==0) {
            r[0]=w*0.5f;
            r[1]=h;
            r[2]=x;
            r[3]=y;
            x+=r[0];
            w-=r[0];
        }
        else {
            r[0]=w;
            r[1]=h*0.5f;
            r[2]=x;
            r[3]=y;
            y+=r[1];
            h-=r[1];
        }
    }
}
// Build the directional-light shadow matrices. One cascade uses the base
// ortho settings; 2-4 cascades use the split/size entries stored in dirlight.
static void shadowvp(SceneCB* sc) {
    float eye[3]= {
        dl[0], dl[1], dl[2]
    }, at[3]= {
        dl[3], dl[4], dl[5]
    };
    float ldx=at[0]-eye[0], ldy=at[1]-eye[1], ldz=at[2]-eye[2], li=rsq(ldx*ldx+ldy*ldy+ldz*ldz);
    float up[3]= {
        0, 1, 0
    };
    if(ab(ldy*li)>0.92f) {
        up[1]=0;
        up[2]=1;
    }
    M4 lv, op, svp;
    lookat(&lv, eye, at, up);
    int cc=(int)dl[16];
    if(cc<1)cc=1;
    if(cc>4)cc=4;
    sc->shadow_params[0]=(float)cc;
    sc->shadow_params[1]=cam[6];
    sc->shadow_params[2]=cam[7];
    ortho(&op, dl[14], dl[15], dl[12], dl[13]);
    svp=mmul(lv, op);
    for(int i=0;i<4;i++) {
        sc->shadow_cascade_splits[i]=cam[7];
        sc->shadow_cascade_rects[i][0]=sc->shadow_cascade_rects[i][1]=sc->shadow_cascade_rects[i][2]=sc->shadow_cascade_rects[i][3]=0;
        cpy(sc->shadow_cascade_view_proj[i], svp.m, 64);
    }
    if(cc>1) {
        float prev=cam[6];
        for(int c=0;c<cc;c++) {
            int b=19+c*5;
            float sf=dl[b], mn=prev+0.001f;
            if(mn>cam[7])mn=cam[7];
            if(sf<mn)sf=mn;
            if(sf>cam[7])sf=cam[7];
            ortho(&op, dl[b+1], dl[b+2], dl[b+3], dl[b+4]);
            svp=mmul(lv, op);
            cpy(sc->shadow_cascade_view_proj[c], svp.m, 64);
            sc->shadow_cascade_splits[c]=sf;
            atlas(c, cc, sc->shadow_cascade_rects[c]);
            prev=sf;
            if(c==0)cpy(sc->shadow_view_proj, svp.m, 64);
        }
        sc->shadow_params[2]=sc->shadow_cascade_splits[cc-1];
    }
    else {
        atlas(0, 1, sc->shadow_cascade_rects[0]);
        cpy(sc->shadow_view_proj, svp.m, 64);
        cpy(sc->shadow_cascade_view_proj[0], svp.m, 64);
        sc->shadow_cascade_splits[0]=dl[13];
    }
    cpy(sc->prev_shadow_view_proj, sc->shadow_view_proj, 64);
}
static int comps(int ty) {
    return (ty==1||ty==4)?1:(ty==2||ty==5)?2:(ty==3||ty==6)?3:(ty==7)?4:0;
}
static int isint(int ty) {
    return ty>=1&&ty<=3;
}
// Timeline evaluation for compact key streams.
// Each track points to frame numbers in kfr[] and to either ki[] or kf[].
static int tr_frame(Tr* r, int k) {
    return kfr[r->fs+k];
}
static int tr_i(Tr* r, int k, int c) {
    return ki[r->ds+k*r->comp+c];
}
static float tr_f(Tr* r, int k, int c) {
    return kf[r->ds+k*r->comp+c];
}
// Evaluate one timeline track at the sampled frame and write the result directly
// into the live command, camera, light or user-variable array.
//
// Important editor-compatibility detail:
//   TL_LERP does NOT mean "hold the previous key until the next key".
//   The editor always interpolates numeric values between surrounding keys.
//   The option only decides whether the sampled frame is fractional (smooth)
//   or rounded down to an integer timeline frame (stepped at timeline FPS).
static void apply_track(Tr* r, float fr) {
    int a=-1, b=-1, i, n=r->count;
    int oi[4]= {
        0, 0, 0, 0
    };
    float A[16], B[16], O[16];
    Q qq;
    zmem(A, sizeof(A));
    zmem(B, sizeof(B));
    zmem(O, sizeof(O));
    // Pick the nearest key at or before fr and the nearest key at or after fr.
        for(i=0;i<n;i++) {
        int kf0=tr_frame(r, i);
        if((float)kf0<=fr)a=i;
        if((float)kf0>=fr) {
            b=i;
            break;
        }
    }
    if(a<0)a=b>=0?b:0;
    if(b<0)b=a;
    if(r->integral) {
        // Integral tracks are always stepped. Currently this is mainly command enabled.
                for(i=0;i<r->comp&&i<4;i++)oi[i]=tr_i(r, a, i);
    }
    else {
        for(i=0;i<r->comp&&i<16;i++) {
            A[i]=tr_f(r, a, i);
            B[i]=tr_f(r, b, i);
            O[i]=A[i];
        }
        if(a!=b) {
            int fa=tr_frame(r, a), fb=tr_frame(r, b);
            float tt=fb>fa?(fr-(float)fa)/(float)(fb-fa):0;
            tt=cl(tt, 0, 1);
            if(r->kind==2) {
                // Command transform: position + quaternion + scale.
                                for(i=0;i<3;i++)O[i]=lerp(A[i], B[i], tt);
                qq=ql(qfa(A+3), qfa(B+3), tt);
                O[3]=qq.x;
                O[4]=qq.y;
                O[5]=qq.z;
                O[6]=qq.w;
                for(i=7;i<10;i++)O[i]=lerp(A[i], B[i], tt);
            }
            else if(r->kind==4) {
                // Camera: interpolate yaw as an angle so it wraps correctly.
                                for(i=0;i<8;i++)O[i]=(i==3)?lerpa(A[i], B[i], tt):lerp(A[i], B[i], tt);
            }
            else {
                int cnt=r->comp;
                // User rotation sources can be stored either as Euler float3 or quaternion float4.
                                if(r->kind==1 && r->target>=0&&r->target<UVN && uv[r->target].src==3 && uv[r->target].type==7) {
                    qq=ql(qfa(A), qfa(B), tt);
                    O[0]=qq.x;
                    O[1]=qq.y;
                    O[2]=qq.z;
                    O[3]=qq.w;
                }
                else {
                    for(i=0;i<cnt&&i<16;i++)O[i]=lerp(A[i], B[i], tt);
                }
            }
        }
    }
    if(r->kind==1 && r->target>=0&&r->target<UVN) {
        int c=comps(uv[r->target].type);
        for(i=0;i<c&&i<4;i++) {
            if(isint(uv[r->target].type))uv[r->target].iv[i]=oi[i];
            else uv[r->target].fv[i]=O[i];
        }
        if(uv[r->target].src_cmd>=0&&uv[r->target].src_cmd<CMDN) {
            Cmd* cc=cmd+uv[r->target].src_cmd;
            if(uv[r->target].src==2)for(i=0;i<3;i++)cc->pos[i]=O[i];
            else if(uv[r->target].src==3) {
                qq=uv[r->target].type==7?qfa(O):qfe(O);
                cc->q[0]=qq.x;
                cc->q[1]=qq.y;
                cc->q[2]=qq.z;
                cc->q[3]=qq.w;
            }
            else if(uv[r->target].src==4)for(i=0;i<3;i++)cc->scl[i]=O[i];
        }
        else if(uv[r->target].src==6) {
            cam[3]=wrap(O[0]);
            cam[4]=cl(O[1], -1.50f, 1.50f);
        }
    }
    else if(r->kind==2 && r->target>=0&&r->target<CMDN) {
        Cmd* c=cmd+r->target;
        for(i=0;i<3;i++)c->pos[i]=O[i];
        for(i=0;i<4;i++)c->q[i]=O[3+i];
        for(i=0;i<3;i++)c->scl[i]=O[7+i];
    }
    else if(r->kind==3 && r->target>=0&&r->target<CMDN) {
        cmd[r->target].enabled=oi[0]!=0;
    }
    else if(r->kind==4) {
        for(i=0;i<8;i++)cam[i]=O[i];
        cam[3]=wrap(cam[3]);
        cam[4]=cl(cam[4], -1.50f, 1.50f);
    }
    else if(r->kind==5) {
        for(i=0;i<10;i++)dl[i]=O[i];
    }
}
static void timeline(float sec) {
    if(!TL_ON||TL_LEN<1||TL_FPS<=0)return;
    // FPS is baked from timeline_settings.
        // TL_LERP=1: evaluate at fractional frame positions for smooth playback.
        // TL_LERP=0: quantize to integer frames before sampling. This gives a
        // visible step every timeline frame, while still interpolating between
        // key values exactly like the editor does.
        float end=(float)(TL_LEN-1), fr=sec*(float)TL_FPS;
    if(fr<0)fr=0;
    if(TL_LOOP&&end>0)while(fr>end)fr-=end;
    else if(fr>end)fr=end;
    if(!TL_LERP)fr=(float)((int)(fr+0.0001f));
    for(int i=0;i<TRN;i++)if(tr[i].enabled)apply_track(tr+i, fr);
}
static int invm(M4* a, M4* o) {
    float* m=a->m;
    float v[16], d;
    v[0]=m[5]*m[10]*m[15]-m[5]*m[11]*m[14]-m[9]*m[6]*m[15]+m[9]*m[7]*m[14]+m[13]*m[6]*m[11]-m[13]*m[7]*m[10];
    v[4]=-m[4]*m[10]*m[15]+m[4]*m[11]*m[14]+m[8]*m[6]*m[15]-m[8]*m[7]*m[14]-m[12]*m[6]*m[11]+m[12]*m[7]*m[10];
    v[8]=m[4]*m[9]*m[15]-m[4]*m[11]*m[13]-m[8]*m[5]*m[15]+m[8]*m[7]*m[13]+m[12]*m[5]*m[11]-m[12]*m[7]*m[9];
    v[12]=-m[4]*m[9]*m[14]+m[4]*m[10]*m[13]+m[8]*m[5]*m[14]-m[8]*m[6]*m[13]-m[12]*m[5]*m[10]+m[12]*m[6]*m[9];
    v[1]=-m[1]*m[10]*m[15]+m[1]*m[11]*m[14]+m[9]*m[2]*m[15]-m[9]*m[3]*m[14]-m[13]*m[2]*m[11]+m[13]*m[3]*m[10];
    v[5]=m[0]*m[10]*m[15]-m[0]*m[11]*m[14]-m[8]*m[2]*m[15]+m[8]*m[3]*m[14]+m[12]*m[2]*m[11]-m[12]*m[3]*m[10];
    v[9]=-m[0]*m[9]*m[15]+m[0]*m[11]*m[13]+m[8]*m[1]*m[15]-m[8]*m[3]*m[13]-m[12]*m[1]*m[11]+m[12]*m[3]*m[9];
    v[13]=m[0]*m[9]*m[14]-m[0]*m[10]*m[13]-m[8]*m[1]*m[14]+m[8]*m[2]*m[13]+m[12]*m[1]*m[10]-m[12]*m[2]*m[9];
    v[2]=m[1]*m[6]*m[15]-m[1]*m[7]*m[14]-m[5]*m[2]*m[15]+m[5]*m[3]*m[14]+m[13]*m[2]*m[7]-m[13]*m[3]*m[6];
    v[6]=-m[0]*m[6]*m[15]+m[0]*m[7]*m[14]+m[4]*m[2]*m[15]-m[4]*m[3]*m[14]-m[12]*m[2]*m[7]+m[12]*m[3]*m[6];
    v[10]=m[0]*m[5]*m[15]-m[0]*m[7]*m[13]-m[4]*m[1]*m[15]+m[4]*m[3]*m[13]+m[12]*m[1]*m[7]-m[12]*m[3]*m[5];
    v[14]=-m[0]*m[5]*m[14]+m[0]*m[6]*m[13]+m[4]*m[1]*m[14]-m[4]*m[2]*m[13]-m[12]*m[1]*m[6]+m[12]*m[2]*m[5];
    v[3]=-m[1]*m[6]*m[11]+m[1]*m[7]*m[10]+m[5]*m[2]*m[11]-m[5]*m[3]*m[10]-m[9]*m[2]*m[7]+m[9]*m[3]*m[6];
    v[7]=m[0]*m[6]*m[11]-m[0]*m[7]*m[10]-m[4]*m[2]*m[11]+m[4]*m[3]*m[10]+m[8]*m[2]*m[7]-m[8]*m[3]*m[6];
    v[11]=-m[0]*m[5]*m[11]+m[0]*m[7]*m[9]+m[4]*m[1]*m[11]-m[4]*m[3]*m[9]-m[8]*m[1]*m[7]+m[8]*m[3]*m[5];
    v[15]=m[0]*m[5]*m[10]-m[0]*m[6]*m[9]-m[4]*m[1]*m[10]+m[4]*m[2]*m[9]+m[8]*m[1]*m[6]-m[8]*m[2]*m[5];
    d=m[0]*v[0]+m[1]*v[4]+m[2]*v[8]+m[3]*v[12];
    if(d==0) {
        mid(o);
        return 0;
    }
    d=1.0f/d;
    for(int i=0;i<16;i++)o->m[i]=v[i]*d;
    return 1;
}
// UserCB is rebuilt for each draw. Global user variables are written first;
// command parameters can then override the first slots for material data.
static void fill_user_base(UserCB* u) {
    int i, j;
    zmem(u, sizeof(*u));
    for(i=0;i<UVN&&i<64;i++) {
        if(isint(uv[i].type)) cpy(u->i[i], uv[i].iv, comps(uv[i].type)*4);
        else for(j=0;j<comps(uv[i].type);j++)u->f[i][j]=uv[i].fv[j];
    }
}
static void fill_user_cmd(UserCB* u, Cmd* c) {
    int i, j, pi;
    fill_user_base(u);
    for(i=0;i<c->pc&&i<64;i++) {
        pi=c->pst+i;
        if(pi<0||pi>=PN)continue;
        if(isint(par[pi].type)) cpy(u->i[i], par[pi].iv, comps(par[pi].type)*4);
        else for(j=0;j<comps(par[pi].type);j++)u->f[i][j]=par[pi].fv[j];
    }
}
static void clear_vals(Cmd* c, float* cc, float* dc) {
    int i;
    for(i=0;i<4;i++)cc[i]=c->cc[i];
    *dc=c->dc;
    if(c->ccs>=0&&c->ccs<UVN&&uv[c->ccs].type==7)for(i=0;i<4;i++)cc[i]=uv[c->ccs].fv[i];
    if(c->dcs>=0&&c->dcs<UVN&&uv[c->dcs].type==4)*dc=cl(uv[c->dcs].fv[0], 0, 1);
}
static HRESULT compile(const char* src, unsigned int len, const char* e, const char* m, ID3DBlob** b) {
    ID3DBlob* er=0;
    HRESULT hr=D3DCompile(src, len, 0, 0, 0, e, m, D3DCOMPILE_OPTIMIZATION_LEVEL3, 0, b, &er);
    if(er)ID3D10Blob_Release(er);
    return hr;
}
// Compile embedded HLSL strings and create a POSITION/NORMAL/TEXCOORD layout
// when the shader accepts primitive geometry.
static void init_shaders() {
    D3D11_INPUT_ELEMENT_DESC il[3];
    zmem(il, sizeof(il));
    il[0].SemanticName="POSITION";
    il[0].Format=DXGI_FORMAT_R32G32B32_FLOAT;
    il[0].AlignedByteOffset=0;
    il[0].InputSlotClass=D3D11_INPUT_PER_VERTEX_DATA;
    il[1].SemanticName="NORMAL";
    il[1].Format=DXGI_FORMAT_R32G32B32_FLOAT;
    il[1].AlignedByteOffset=12;
    il[1].InputSlotClass=D3D11_INPUT_PER_VERTEX_DATA;
    il[2].SemanticName="TEXCOORD";
    il[2].Format=DXGI_FORMAT_R32G32_FLOAT;
    il[2].AlignedByteOffset=24;
    il[2].InputSlotClass=D3D11_INPUT_PER_VERTEX_DATA;
    for(int i=0;i<SHN;i++) {
        ID3DBlob *vs=0, *ps=0;
        if(SUCCEEDED(compile(sh[i].src, sh[i].len, "VSMain", "vs_5_0", &vs))&&SUCCEEDED(compile(sh[i].src, sh[i].len, "PSMain", "ps_5_0", &ps))) {
            ID3D11Device_CreateVertexShader(dev, ID3D10Blob_GetBufferPointer(vs), ID3D10Blob_GetBufferSize(vs), 0, &sh[i].vs);
            ID3D11Device_CreatePixelShader(dev, ID3D10Blob_GetBufferPointer(ps), ID3D10Blob_GetBufferSize(ps), 0, &sh[i].ps);
            ID3D11Device_CreateInputLayout(dev, il, 3, ID3D10Blob_GetBufferPointer(vs), ID3D10Blob_GetBufferSize(vs), &sh[i].il);
        }
        if(vs)ID3D10Blob_Release(vs);
        if(ps)ID3D10Blob_Release(ps);
    }
}
static void mkbuf(int id, float* v, unsigned int bytes) {
    D3D11_BUFFER_DESC d;
    D3D11_SUBRESOURCE_DATA s;
    zmem(&d, sizeof(d));
    zmem(&s, sizeof(s));
    d.ByteWidth=bytes;
    d.BindFlags=D3D11_BIND_VERTEX_BUFFER;
    s.pSysMem=v;
    ID3D11Device_CreateBuffer(dev, &d, &s, &prim_vb[id]);
}
static void pv(float* v, int* n, float x, float y, float z, float nx, float ny, float nz, float u, float vv) {
    int i=*n;
    v[i+0]=x;
    v[i+1]=y;
    v[i+2]=z;
    v[i+3]=nx;
    v[i+4]=ny;
    v[i+5]=nz;
    v[i+6]=u;
    v[i+7]=vv;
    *n=i+8;
}
// Create built-in procedural vertex buffers. Shader-only procedural draws use
// no input layout/VB; primitive draws use these tiny expanded triangle lists.
static void init_prims() {
    static float cube[]= {
        -1, -1, -1, 0, 0, -1, 0, 1, 1, 1, -1, 0, 0, -1, 1, 0, 1, -1, -1, 0, 0, -1, 1, 1, -1, -1, -1, 0, 0, -1, 0, 1, -1, 1, -1, 0, 0, -1, 0, 0, 1, 1, -1, 0, 0, -1, 1, 0, -1, -1, 1, 0, 0, 1, 0, 1, 1, -1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, -1, -1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, -1, 1, 1, 0, 0, 1, 0, 0, -1, -1, -1, -1, 0, 0, 0, 1, -1, -1, 1, -1, 0, 0, 1, 1, -1, 1, 1, -1, 0, 0, 1, 0, -1, -1, -1, -1, 0, 0, 0, 1, -1, 1, 1, -1, 0, 0, 1, 0, -1, 1, -1, -1, 0, 0, 0, 0, 1, -1, -1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, -1, 1, 1, 0, 0, 1, 1, 1, -1, -1, 1, 0, 0, 0, 1, 1, 1, -1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, -1, -1, -1, 0, -1, 0, 0, 1, 1, -1, -1, 0, -1, 0, 1, 1, 1, -1, 1, 0, -1, 0, 1, 0, -1, -1, -1, 0, -1, 0, 0, 1, 1, -1, 1, 0, -1, 0, 1, 0, -1, -1, 1, 0, -1, 0, 0, 0, -1, 1, -1, 0, 1, 0, 0, 1, -1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, -1, 1, -1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, -1, 0, 1, 0, 1, 1
    };
    static float quad[]= {
        -1, -1, 0, 0, 0, 1, 0, 1, 1, -1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, -1, -1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, -1, 1, 0, 0, 0, 1, 0, 0
    };
    static float tet[]= {
        1, 1, 1, 0.57735f, 0.57735f, 0.57735f, 0.5f, 0, -1, -1, 1, 0.57735f, 0.57735f, 0.57735f, 0, 1, -1, 1, -1, 0.57735f, 0.57735f, 0.57735f, 1, 1, 1, 1, 1, 0.57735f, -0.57735f, 0.57735f, 0.5f, 0, 1, -1, -1, 0.57735f, -0.57735f, 0.57735f, 0, 1, -1, -1, 1, 0.57735f, -0.57735f, 0.57735f, 1, 1, 1, 1, 1, 0.57735f, 0.57735f, -0.57735f, 0.5f, 0, -1, 1, -1, 0.57735f, 0.57735f, -0.57735f, 0, 1, 1, -1, -1, 0.57735f, 0.57735f, -0.57735f, 1, 1, -1, -1, 1, -0.57735f, -0.57735f, -0.57735f, 0.5f, 0, 1, -1, -1, -0.57735f, -0.57735f, -0.57735f, 0, 1, -1, 1, -1, -0.57735f, -0.57735f, -0.57735f, 1, 1
    };
    static float fs[]= {
        -1, -1, 0, 0, 0, 1, 0, 1, -1, 3, 0, 0, 0, 1, 0, -1, 3, -1, 0, 0, 0, 1, 2, 1
    };
    // The editor builds the sphere through an indexed mesh and calls
        // res_add_oriented_tri(), which flips every generated sphere triangle so
        // its winding is outward for the D3D11 rasterizer state.  The first 64k
        // rewrite expanded the triangles but kept the pre-flip order.  That rendered
        // the sphere with the opposite face orientation: color could still appear in
        // some views, but the shadow prepass wrote the wrong side of the sphere, so
        // the receiver sampled shadows that seemed to rotate/swim with the camera.
        //
        // Keep this expanded list in the same post-flip order as resources.cpp:
        //   top cap:    i0,i3,i1
        //   middle A:   i0,i2,i1
        //   middle B:   i2,i3,i1
        //   bottom cap: i0,i2,i1
        static float sph[2880*8];
    int n=0;
    for(int r=0;r<16;r++) {
        for(int s=0;s<32;s++) {
            float v0=(float)r/16.0f, v1=(float)(r+1)/16.0f, u0=(float)s/32.0f, u1=(float)(s+1)/32.0f;
            float th0=v0*LT_PI, th1=v1*LT_PI, ph0=u0*6.28318530718f, ph1=u1*6.28318530718f;
            float sr0=sn(th0), sr1=sn(th1);
            float p0[8]= {
                sr0*cs(ph0), cs(th0), sr0*sn(ph0), sr0*cs(ph0), cs(th0), sr0*sn(ph0), u0, v0
            };
            float p1[8]= {
                sr1*cs(ph0), cs(th1), sr1*sn(ph0), sr1*cs(ph0), cs(th1), sr1*sn(ph0), u0, v1
            };
            float p2[8]= {
                sr0*cs(ph1), cs(th0), sr0*sn(ph1), sr0*cs(ph1), cs(th0), sr0*sn(ph1), u1, v0
            };
            float p3[8]= {
                sr1*cs(ph1), cs(th1), sr1*sn(ph1), sr1*cs(ph1), cs(th1), sr1*sn(ph1), u1, v1
            };
            if(r==0) {
                pv(sph, &n, p0[0], p0[1], p0[2], p0[3], p0[4], p0[5], p0[6], p0[7]);
                pv(sph, &n, p3[0], p3[1], p3[2], p3[3], p3[4], p3[5], p3[6], p3[7]);
                pv(sph, &n, p1[0], p1[1], p1[2], p1[3], p1[4], p1[5], p1[6], p1[7]);
            }
            else if(r==15) {
                pv(sph, &n, p0[0], p0[1], p0[2], p0[3], p0[4], p0[5], p0[6], p0[7]);
                pv(sph, &n, p2[0], p2[1], p2[2], p2[3], p2[4], p2[5], p2[6], p2[7]);
                pv(sph, &n, p1[0], p1[1], p1[2], p1[3], p1[4], p1[5], p1[6], p1[7]);
            }
            else {
                pv(sph, &n, p0[0], p0[1], p0[2], p0[3], p0[4], p0[5], p0[6], p0[7]);
                pv(sph, &n, p2[0], p2[1], p2[2], p2[3], p2[4], p2[5], p2[6], p2[7]);
                pv(sph, &n, p1[0], p1[1], p1[2], p1[3], p1[4], p1[5], p1[6], p1[7]);
                pv(sph, &n, p2[0], p2[1], p2[2], p2[3], p2[4], p2[5], p2[6], p2[7]);
                pv(sph, &n, p3[0], p3[1], p3[2], p3[3], p3[4], p3[5], p3[6], p3[7]);
                pv(sph, &n, p1[0], p1[1], p1[2], p1[3], p1[4], p1[5], p1[6], p1[7]);
            }
        }
    }
    mkbuf(1, cube, sizeof(cube));
    mkbuf(2, quad, sizeof(quad));
    mkbuf(3, tet, sizeof(tet));
    mkbuf(4, sph, (unsigned int)(n*4));
    mkbuf(5, fs, sizeof(fs));
}
static int rtw(int i) {
    int d=rtd[i].div, w;
    if(d>0)w=(RW+d-1)/d;
    else w=rtd[i].w>0?rtd[i].w:RW;
    return w>0?w:1;
}
static int rth(int i) {
    int d=rtd[i].div, h;
    if(d>0)h=(RH+d-1)/d;
    else h=rtd[i].h>0?rtd[i].h:RH;
    return h>0?h:1;
}
static DXGI_FORMAT sfmt(DXGI_FORMAT f) {
    if(f==DXGI_FORMAT_D24_UNORM_S8_UINT||f==DXGI_FORMAT_R24G8_TYPELESS)return DXGI_FORMAT_R24G8_TYPELESS;
    if(f==DXGI_FORMAT_D32_FLOAT||f==DXGI_FORMAT_R32_TYPELESS)return DXGI_FORMAT_R32_TYPELESS;
    return f;
}
static DXGI_FORMAT srvfmt(DXGI_FORMAT f) {
    if(f==DXGI_FORMAT_D24_UNORM_S8_UINT||f==DXGI_FORMAT_R24G8_TYPELESS)return DXGI_FORMAT_R24_UNORM_X8_TYPELESS;
    if(f==DXGI_FORMAT_D32_FLOAT||f==DXGI_FORMAT_R32_TYPELESS)return DXGI_FORMAT_R32_FLOAT;
    return f;
}
// Allocate internal render textures requested by the project. They replace file
// textures in the 64k path and support post-processing chains.
static void init_rts() {
    for(int i=0;i<RTN;i++) {
        D3D11_TEXTURE2D_DESC d;
        zmem(&d, sizeof(d));
        d.Width=rtw(i);
        d.Height=rth(i);
        d.MipLevels=1;
        d.ArraySize=1;
        d.Format=sfmt((DXGI_FORMAT)rtd[i].fmt);
        d.SampleDesc.Count=1;
        d.BindFlags=(rtd[i].rtv?D3D11_BIND_RENDER_TARGET:0)|(rtd[i].srv?D3D11_BIND_SHADER_RESOURCE:0)|(rtd[i].uav?D3D11_BIND_UNORDERED_ACCESS:0);
        if(!d.BindFlags)d.BindFlags=D3D11_BIND_RENDER_TARGET|D3D11_BIND_SHADER_RESOURCE;
        if(SUCCEEDED(ID3D11Device_CreateTexture2D(dev, &d, 0, &rt_tex[i]))) {
            if(rtd[i].rtv)ID3D11Device_CreateRenderTargetView(dev, (ID3D11Resource*)rt_tex[i], 0, &rt_rtv[i]);
            if(rtd[i].srv) {
                D3D11_SHADER_RESOURCE_VIEW_DESC sv;
                zmem(&sv, sizeof(sv));
                sv.Format=srvfmt((DXGI_FORMAT)rtd[i].fmt);
                sv.ViewDimension=D3D11_SRV_DIMENSION_TEXTURE2D;
                sv.Texture2D.MipLevels=1;
                ID3D11Device_CreateShaderResourceView(dev, (ID3D11Resource*)rt_tex[i], &sv, &rt_srv[i]);
            }
        }
    }
}
// Create the main depth buffer and the shared shadow-map atlas. Both also have
// SRVs so post effects and material shaders can sample them.
static void init_depth_shadow() {
    D3D11_TEXTURE2D_DESC d;
    D3D11_DEPTH_STENCIL_VIEW_DESC dv;
    D3D11_SHADER_RESOURCE_VIEW_DESC sv;
    zmem(&d, sizeof(d));
    d.Width=RW;
    d.Height=RH;
    d.MipLevels=1;
    d.ArraySize=1;
    d.Format=DXGI_FORMAT_R24G8_TYPELESS;
    d.SampleDesc.Count=1;
    d.BindFlags=D3D11_BIND_DEPTH_STENCIL|D3D11_BIND_SHADER_RESOURCE;
    if(SUCCEEDED(ID3D11Device_CreateTexture2D(dev, &d, 0, &depth_tex))) {
        zmem(&dv, sizeof(dv));
        zmem(&sv, sizeof(sv));
        dv.Format=DXGI_FORMAT_D24_UNORM_S8_UINT;
        dv.ViewDimension=D3D11_DSV_DIMENSION_TEXTURE2D;
        ID3D11Device_CreateDepthStencilView(dev, (ID3D11Resource*)depth_tex, &dv, &dsv);
        sv.Format=DXGI_FORMAT_R24_UNORM_X8_TYPELESS;
        sv.ViewDimension=D3D11_SRV_DIMENSION_TEXTURE2D;
        sv.Texture2D.MipLevels=1;
        ID3D11Device_CreateShaderResourceView(dev, (ID3D11Resource*)depth_tex, &sv, &depth_srv);
    }
    zmem(&d, sizeof(d));
    d.Width=LT_SHADOW_W;
    d.Height=LT_SHADOW_H;
    d.MipLevels=1;
    d.ArraySize=1;
    d.Format=DXGI_FORMAT_R24G8_TYPELESS;
    d.SampleDesc.Count=1;
    d.BindFlags=D3D11_BIND_DEPTH_STENCIL|D3D11_BIND_SHADER_RESOURCE;
    if(SUCCEEDED(ID3D11Device_CreateTexture2D(dev, &d, 0, &shadow_tex))) {
        zmem(&dv, sizeof(dv));
        zmem(&sv, sizeof(sv));
        dv.Format=DXGI_FORMAT_D24_UNORM_S8_UINT;
        dv.ViewDimension=D3D11_DSV_DIMENSION_TEXTURE2D;
        ID3D11Device_CreateDepthStencilView(dev, (ID3D11Resource*)shadow_tex, &dv, &shadow_dsv);
        sv.Format=DXGI_FORMAT_R24_UNORM_X8_TYPELESS;
        sv.ViewDimension=D3D11_SRV_DIMENSION_TEXTURE2D;
        sv.Texture2D.MipLevels=1;
        ID3D11Device_CreateShaderResourceView(dev, (ID3D11Resource*)shadow_tex, &sv, &shadow_srv);
    }
}
static void init_states() {
    D3D11_SAMPLER_DESC sp;
    zmem(&sp, sizeof(sp));
    sp.Filter=D3D11_FILTER_MIN_MAG_MIP_LINEAR;
    sp.AddressU=sp.AddressV=sp.AddressW=D3D11_TEXTURE_ADDRESS_WRAP;
    sp.MaxLOD=3.402823466e38f;
    ID3D11Device_CreateSamplerState(dev, &sp, &smp_lin);
    sp.Filter=D3D11_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT;
    sp.ComparisonFunc=D3D11_COMPARISON_LESS_EQUAL;
    sp.AddressU=sp.AddressV=sp.AddressW=D3D11_TEXTURE_ADDRESS_BORDER;
    sp.BorderColor[0]=sp.BorderColor[1]=sp.BorderColor[2]=sp.BorderColor[3]=1.0f;
    ID3D11Device_CreateSamplerState(dev, &sp, &smp_cmp);
    for(int i=0;i<4;i++) {
        D3D11_DEPTH_STENCIL_DESC dd;
        zmem(&dd, sizeof(dd));
        dd.DepthEnable=(i&1)!=0;
        dd.DepthWriteMask=(i&2)?D3D11_DEPTH_WRITE_MASK_ALL:D3D11_DEPTH_WRITE_MASK_ZERO;
        /* Keep the tiny-player depth test as LESS_EQUAL, matching the previous working 64k path.
           The editor uses LESS for the interactive viewport, but this standalone path also
           uses generated primitive shadow shaders and very small procedural meshes; LEQUAL
           is more robust for the shadow/color depth state and fixes the black test2 output
           introduced in v7. */ dd.DepthFunc=D3D11_COMPARISON_LESS_EQUAL;
        ID3D11Device_CreateDepthStencilState(dev, &dd, &ds[i]);
        D3D11_BLEND_DESC bd;
        zmem(&bd, sizeof(bd));
        bd.RenderTarget[0].BlendEnable=(i&1)!=0;
        bd.RenderTarget[0].SrcBlend=D3D11_BLEND_SRC_ALPHA;
        bd.RenderTarget[0].DestBlend=D3D11_BLEND_INV_SRC_ALPHA;
        bd.RenderTarget[0].BlendOp=D3D11_BLEND_OP_ADD;
        bd.RenderTarget[0].SrcBlendAlpha=D3D11_BLEND_ONE;
        bd.RenderTarget[0].DestBlendAlpha=D3D11_BLEND_INV_SRC_ALPHA;
        bd.RenderTarget[0].BlendOpAlpha=D3D11_BLEND_OP_ADD;
        bd.RenderTarget[0].RenderTargetWriteMask=(i&2)?D3D11_COLOR_WRITE_ENABLE_ALL:0;
        ID3D11Device_CreateBlendState(dev, &bd, &bs[i]);
    }
    for(int i=0;i<2;i++) {
        D3D11_RASTERIZER_DESC rd;
        zmem(&rd, sizeof(rd));
        rd.FillMode=D3D11_FILL_SOLID;
        rd.CullMode=i?D3D11_CULL_BACK:D3D11_CULL_NONE;
        rd.DepthClipEnable=TRUE;
        ID3D11Device_CreateRasterizerState(dev, &rd, &rs[i]);
    }
}
static void cb_make(ID3D11Buffer** b, unsigned int sz) {
    D3D11_BUFFER_DESC d;
    zmem(&d, sizeof(d));
    d.ByteWidth=(sz+15)&~15;
    d.Usage=D3D11_USAGE_DYNAMIC;
    d.BindFlags=D3D11_BIND_CONSTANT_BUFFER;
    d.CPUAccessFlags=D3D11_CPU_ACCESS_WRITE;
    ID3D11Device_CreateBuffer(dev, &d, 0, b);
}
static void cb_up(ID3D11Buffer* b, void* data, unsigned int sz) {
    D3D11_MAPPED_SUBRESOURCE m;
    if(SUCCEEDED(ID3D11DeviceContext_Map(ctx, (ID3D11Resource*)b, 0, D3D11_MAP_WRITE_DISCARD, 0, &m))) {
        cpy(m.pData, data, sz);
        ID3D11DeviceContext_Unmap(ctx, (ID3D11Resource*)b, 0);
    }
}
static ID3D11ShaderResourceView* srvof(int s) {
    if(s>=0&&s<RTN)return rt_srv[s];
    if(s==-2)return depth_srv;
    if(s==-3)return shadow_srv;
    return 0;
}
static ID3D11RenderTargetView* rtvof(int t) {
    if(t==-2)return rtv;
    if(t>=0&&t<RTN)return rt_rtv[t];
    return 0;
}
static void set_target(Cmd* c) {
    ID3D11ShaderResourceView* nulls[16];
    zmem(nulls, sizeof(nulls));
    ID3D11DeviceContext_PSSetShaderResources(ctx, 0, 16, nulls);
    ID3D11DeviceContext_VSSetShaderResources(ctx, 0, 16, nulls);
    ID3D11RenderTargetView* rv=rtvof(c->rt);
    ID3D11DepthStencilView* dv=(c->dep==-2)?dsv:0;
    ID3D11DeviceContext_OMSetRenderTargets(ctx, rv?1:0, rv?&rv:0, dv);
    D3D11_VIEWPORT vp;
    zmem(&vp, sizeof(vp));
    if(c->rt>=0&&c->rt<RTN) {
        vp.Width=(float)rtw(c->rt);
        vp.Height=(float)rth(c->rt);
    }
    else if(c->rt==-2) {
        vp.Width=(float)W;
        vp.Height=(float)H;
    }
    else {
        vp.Width=(float)RW;
        vp.Height=(float)RH;
    }
    vp.MinDepth=0;
    vp.MaxDepth=1;
    ID3D11DeviceContext_RSSetViewports(ctx, 1, &vp);
}
static void shadow_draw(Cmd* c) {
    if(!c->enabled||!c->scast||c->shs<0||c->shs>=SHN||!sh[c->shs].vs)return;
    UserCB uc;
    ObjectCB oc;
    M4 w;
    world(c, &w);
    cpy(oc.world, w.m, 64);
    fill_user_cmd(&uc, c);
    cb_up(object_cb, &oc, sizeof(oc));
    cb_up(user_cb, &uc, sizeof(uc));
    ID3D11DeviceContext_RSSetState(ctx, rs[c->cb?1:0]);
    ID3D11DeviceContext_VSSetConstantBuffers(ctx, 0, 1, &scene_cb);
    ID3D11DeviceContext_VSSetConstantBuffers(ctx, 1, 1, &object_cb);
    ID3D11DeviceContext_VSSetConstantBuffers(ctx, 2, 1, &user_cb);
    if(c->mk>0&&c->mk<6&&prim_vb[c->mk]) {
        unsigned int st=32, off=0;
        ID3D11DeviceContext_IASetInputLayout(ctx, sh[c->shs].il);
        ID3D11DeviceContext_IASetVertexBuffers(ctx, 0, 1, &prim_vb[c->mk], &st, &off);
    }
    else {
        ID3D11DeviceContext_IASetInputLayout(ctx, 0);
        ID3D11DeviceContext_IASetVertexBuffers(ctx, 0, 0, 0, 0, 0);
    }
    ID3D11DeviceContext_IASetIndexBuffer(ctx, 0, DXGI_FORMAT_R32_UINT, 0);
    ID3D11DeviceContext_IASetPrimitiveTopology(ctx, c->topology?D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST:D3D11_PRIMITIVE_TOPOLOGY_POINTLIST);
    ID3D11DeviceContext_VSSetShader(ctx, sh[c->shs].vs, 0, 0);
    ID3D11DeviceContext_PSSetShader(ctx, 0, 0, 0);
    ID3D11DeviceContext_DrawInstanced(ctx, c->vc, c->ic, 0, 0);
}
// Render all shadow-casting commands into the atlas before the main pass.
static void shadowpass(SceneCB* sc) {
    if(!shadow_dsv)return;
    int need=0;
    for(int i=0;i<CMDN;i++)if(cmd[i].enabled&&cmd[i].scast)need=1;
    if(!need)return;
    ID3D11ShaderResourceView* nulls[16];
    zmem(nulls, sizeof(nulls));
    ID3D11DeviceContext_PSSetShaderResources(ctx, 0, 16, nulls);
    ID3D11DeviceContext_VSSetShaderResources(ctx, 0, 16, nulls);
    ID3D11DeviceContext_OMSetRenderTargets(ctx, 0, 0, shadow_dsv);
    ID3D11DeviceContext_ClearDepthStencilView(ctx, shadow_dsv, D3D11_CLEAR_DEPTH, 1, 0);
    ID3D11DeviceContext_OMSetDepthStencilState(ctx, ds[3], 0);
    float bf[4]= {
        0, 0, 0, 0
    };
    ID3D11DeviceContext_OMSetBlendState(ctx, bs[0], bf, 0xffffffff);
    int cc=(int)sc->shadow_params[0];
    if(cc<1)cc=1;
    if(cc>4)cc=4;
    for(int ci=0;ci<cc;ci++) {
        float* r=sc->shadow_cascade_rects[ci];
        D3D11_VIEWPORT vp;
        zmem(&vp, sizeof(vp));
        vp.TopLeftX=r[2]*(float)LT_SHADOW_W;
        vp.TopLeftY=r[3]*(float)LT_SHADOW_H;
        vp.Width=(r[0]>0?r[0]:1)*(float)LT_SHADOW_W;
        vp.Height=(r[1]>0?r[1]:1)*(float)LT_SHADOW_H;
        vp.MinDepth=0;
        vp.MaxDepth=1;
        ID3D11DeviceContext_RSSetViewports(ctx, 1, &vp);
        SceneCB t=*sc;
        cpy(t.shadow_view_proj, sc->shadow_cascade_view_proj[ci], 64);
        cb_up(scene_cb, &t, sizeof(t));
        for(int i=0;i<CMDN;i++)shadow_draw(cmd+i);
    }
    cb_up(scene_cb, sc, sizeof(*sc));
}
// Main frame: update animation, render shadows, then execute the command list.
// Draw a tiny, optional FPS overlay directly over the presented window.
// It is compiled out by default because final/demo builds should not show any
// diagnostic text and should not spend even a small amount of time in GDI.
//
// Enable it with /DLT_DEBUG_FPS=1 when you need to check pacing. It uses GDI
// after Present instead of D3D, so it does not add another shader, texture,
// buffer or render pass. Press F1 to toggle it while the program is running.
#if LT_DEBUG_FPS
static char* apu(char* p, unsigned int v) {
    char b[10];
    int n=0;
    if(!v) {
        *p++='0';
        return p;
    }
    while(v&&n<10) {
        b[n++]=(char)('0'+v%10);
        v/=10;
    }
    while(n--)*p++=b[n];
    return p;
}
static char* aps(char* p, const char* s) {
    while(*s)*p++=*s++;
    return p;
}
static void dbg_fps(void) {
    static DWORD last_tick=0, win0=0;
    static unsigned int frames=0, fps=0, avg10=0, maxms=0, maxwin=0;
    DWORD now=GetTickCount();
    if(!last_tick) last_tick=now;
    if(!win0) win0=now;
    // Use wall-clock milliseconds rather than the timeline clock. The timeline
        // may clamp very large deltas to avoid animation jumps, but the debug HUD
        // should report the real frame pacing that the user sees.
        {
        DWORD frame_ms=now-last_tick;
        if(frame_ms>maxwin)maxwin=frame_ms;
        last_tick=now;
    }
    frames++;
    {
        DWORD dt=now-win0;
        if(dt>=500) {
            fps=(unsigned int)((frames*1000u + dt/2u)/dt);
            avg10=(unsigned int)((dt*10u + frames/2u)/frames);
            maxms=maxwin;
            frames=0;
            maxwin=0;
            win0=now;
        }
    }
    if(dbg_on) {
        char txt[128];
        char* p=txt;
        p=aps(p, "FPS ");
        p=apu(p, fps);
        p=aps(p, "  avg ");
        p=apu(p, avg10/10u);
        *p++='.';
        *p++=(char)('0'+(avg10%10u));
        p=aps(p, "ms");
        p=aps(p, "  max ");
        p=apu(p, maxms);
        p=aps(p, "ms");
        p=aps(p, "  rt ");
        p=apu(p, (unsigned int)RW);
        *p++='x';
        p=apu(p, (unsigned int)RH);
        p=aps(p, "  win ");
        p=apu(p, (unsigned int)W);
        *p++='x';
        p=apu(p, (unsigned int)H);
        p=aps(p, LT_VSYNC?"  vsync":"  immediate");
        *p=0;
        HDC dc=GetDC(wh);
        if(dc) {
            SetBkMode(dc, OPAQUE);
            SetBkColor(dc, 0x00000000);
            SetTextColor(dc, 0x00ffffff);
            TextOutA(dc, 12, 12, txt, (int)(p-txt));
            ReleaseDC(wh, dc);
        }
    }
}
#else
static void dbg_fps(void) {
}
#endif
static void render(float sec) {
    cpy(cam, cam0, sizeof(cam));
    cpy(dl, dl0, sizeof(dl));
    timeline(sec);
    float clr[4]= {
        0, 0, 0, 1
    }, bf[4]= {
        0, 0, 0, 0
    };
    SceneCB sc;
    ObjectCB oc;
    M4 vp, ivp;
    zmem(&sc, sizeof(sc));
    viewproj(&vp, sec);
    invm(&vp, &ivp);
    cpy(sc.view_proj, vp.m, 64);
    cpy(sc.prev_view_proj, vp.m, 64);
    cpy(sc.inv_view_proj, ivp.m, 64);
    cpy(sc.prev_inv_view_proj, ivp.m, 64);
    shadowvp(&sc);
    sc.time_vec[0]=sec;
    sc.time_vec[2]=sec*60.0f;
    sc.cam_pos[0]=cam[0];
    sc.cam_pos[1]=cam[1];
    sc.cam_pos[2]=cam[2];
    float cp=cs(cam[4]);
    sc.cam_dir[0]=sn(cam[3])*cp;
    sc.cam_dir[1]=sn(cam[4]);
    sc.cam_dir[2]=cs(cam[3])*cp;
    float ldx=dl[3]-dl[0], ldy=dl[4]-dl[1], ldz=dl[5]-dl[2], li=rsq(ldx*ldx+ldy*ldy+ldz*ldz);
    sc.light_dir[0]=ldx*li;
    sc.light_dir[1]=ldy*li;
    sc.light_dir[2]=ldz*li;
    sc.light_dir[3]=dl[9];
    sc.light_color[0]=dl[6];
    sc.light_color[1]=dl[7];
    sc.light_color[2]=dl[8];
    shadowpass(&sc);
    cb_up(scene_cb, &sc, sizeof(sc));
    ID3D11DeviceContext_ClearRenderTargetView(ctx, rtv, clr);
    if(dsv)ID3D11DeviceContext_ClearDepthStencilView(ctx, dsv, D3D11_CLEAR_DEPTH, 1, 0);
    for(int i=0;i<CMDN;i++) {
        Cmd* c=cmd+i;
        if(!c->enabled)continue;
        set_target(c);
        if(c->type==1) {
            ID3D11RenderTargetView* rv=rtvof(c->rt);
            float cc[4], dc;
            clear_vals(c, cc, &dc);
            if(c->ccen&&rv)ID3D11DeviceContext_ClearRenderTargetView(ctx, rv, cc);
            if(c->cden&&c->dep==-2&&dsv)ID3D11DeviceContext_ClearDepthStencilView(ctx, dsv, D3D11_CLEAR_DEPTH, dc, 0);
        }
        else if(c->type==2 && c->shader>=0&&c->shader<SHN&&sh[c->shader].vs&&sh[c->shader].ps) {
            UserCB uc;
            M4 w;
            world(c, &w);
            cpy(oc.world, w.m, 64);
            fill_user_cmd(&uc, c);
            cb_up(object_cb, &oc, sizeof(oc));
            cb_up(user_cb, &uc, sizeof(uc));
            ID3D11DeviceContext_OMSetDepthStencilState(ctx, ds[(c->dt?1:0)|(c->dw?2:0)], 0);
            ID3D11DeviceContext_RSSetState(ctx, rs[c->cb?1:0]);
            ID3D11DeviceContext_OMSetBlendState(ctx, bs[(c->ab?1:0)|(c->cw?2:0)], bf, 0xffffffff);
            ID3D11DeviceContext_VSSetConstantBuffers(ctx, 0, 1, &scene_cb);
            ID3D11DeviceContext_PSSetConstantBuffers(ctx, 0, 1, &scene_cb);
            ID3D11DeviceContext_VSSetConstantBuffers(ctx, 1, 1, &object_cb);
            ID3D11DeviceContext_PSSetConstantBuffers(ctx, 1, 1, &object_cb);
            ID3D11DeviceContext_VSSetConstantBuffers(ctx, 2, 1, &user_cb);
            ID3D11DeviceContext_PSSetConstantBuffers(ctx, 2, 1, &user_cb);
            ID3D11DeviceContext_PSSetSamplers(ctx, 0, 1, &smp_lin);
            ID3D11DeviceContext_PSSetSamplers(ctx, 1, 1, &smp_cmp);
            for(int t=0;t<c->tc;t++) {
                ID3D11ShaderResourceView* sv=srvof(c->tex[t]);
                ID3D11DeviceContext_PSSetShaderResources(ctx, c->tsl[t], 1, &sv);
            }
            if(c->srecv) {
                ID3D11ShaderResourceView* sv=shadow_srv;
                ID3D11DeviceContext_PSSetShaderResources(ctx, 7, 1, &sv);
            }
            for(int t=0;t<c->sc;t++) {
                ID3D11ShaderResourceView* sv=srvof(c->srv[t]);
                ID3D11DeviceContext_VSSetShaderResources(ctx, c->ssl[t], 1, &sv);
            }
            if(c->mk>0&&c->mk<6&&prim_vb[c->mk]) {
                unsigned int st=32, off=0;
                ID3D11DeviceContext_IASetInputLayout(ctx, sh[c->shader].il);
                ID3D11DeviceContext_IASetVertexBuffers(ctx, 0, 1, &prim_vb[c->mk], &st, &off);
            }
            else {
                ID3D11DeviceContext_IASetInputLayout(ctx, 0);
                ID3D11DeviceContext_IASetVertexBuffers(ctx, 0, 0, 0, 0, 0);
            }
            ID3D11DeviceContext_IASetIndexBuffer(ctx, 0, DXGI_FORMAT_R32_UINT, 0);
            ID3D11DeviceContext_IASetPrimitiveTopology(ctx, c->topology?D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST:D3D11_PRIMITIVE_TOPOLOGY_POINTLIST);
            ID3D11DeviceContext_VSSetShader(ctx, sh[c->shader].vs, 0, 0);
            ID3D11DeviceContext_PSSetShader(ctx, sh[c->shader].ps, 0, 0);
            ID3D11DeviceContext_DrawInstanced(ctx, c->vc, c->ic, 0, 0);
        }
    }
    IDXGISwapChain_Present(swp, LT_VSYNC?1:0, 0);
    dbg_fps();
}
static LRESULT CALLBACK wp(HWND h, UINT m, WPARAM w, LPARAM l) {
    if(m==WM_KEYDOWN&&w==VK_ESCAPE)PostQuitMessage(0);
#if LT_DEBUG_FPS
        // F1 is a runtime toggle for the optional FPS overlay. In release mode
        // LT_DEBUG_FPS is 0, this branch is removed by the preprocessor.
        if(m==WM_KEYDOWN&&w==VK_F1) {
        dbg_on=!dbg_on;
        return 0;
    }
#endif
        if(m==WM_CLOSE||m==WM_DESTROY) {
        PostQuitMessage(0);
        return 0;
    }
    return DefWindowProcA(h, m, w, l);
}
// Return the elapsed seconds between two QPC samples without using 64-bit-to-double conversion.
// MSVC x86 emits the CRT helper __ltod3 for `(double)LARGE_INTEGER.QuadPart`; that helper is
// intentionally unavailable in this /NODEFAULTLIB tiny build.  We only need the delta between
// consecutive frames, so the unsigned 32-bit low-part difference is enough and is wrap-safe as
// long as a single frame does not last several minutes.
static float qpcdt(LARGE_INTEGER* now, LARGE_INTEGER* prev, LARGE_INTEGER* freq) {
    unsigned int dt=(unsigned int)now->LowPart-(unsigned int)prev->LowPart;
    unsigned int fq=(unsigned int)freq->LowPart? (unsigned int)freq->LowPart:1;
    float s=(float)dt/(float)fq;
    if(s>0.10f)s=0.10f;
    return s;
}
void WINAPI WinMainCRTStartup(void) {
    WNDCLASSA wc;
    zmem(&wc, sizeof(wc));
    wc.lpfnWndProc=wp;
    wc.hInstance=GetModuleHandleA(0);
    wc.lpszClassName=LT_WNDCLS;
    RegisterClassA(&wc);
    // Fullscreen is implemented as borderless desktop fullscreen instead of exclusive mode.
        // That keeps startup simple, avoids display-mode changes, and is friendly to demos compressed with UPX.
        // Fullscreen-only size policy: render at the real monitor/backbuffer size.
        // RW/RH are deliberately equal to W/H, so the camera aspect ratio cannot be
        // different from the final presentation aspect ratio.
        W=GetSystemMetrics(SM_CXSCREEN);
    H=GetSystemMetrics(SM_CYSCREEN);
    RW=W;
    RH=H;
    HWND hw=CreateWindowExA(WS_EX_TOPMOST, LT_WNDCLS, "lt64k", WS_POPUP|WS_VISIBLE, 0, 0, W, H, 0, 0, wc.hInstance, 0);
    wh=hw;
    SetWindowPos(hw, HWND_TOPMOST, 0, 0, W, H, SWP_SHOWWINDOW);
    ShowCursor(FALSE);
    DXGI_SWAP_CHAIN_DESC sd;
    zmem(&sd, sizeof(sd));
    sd.BufferCount=1;
    sd.BufferDesc.Width=W;
    sd.BufferDesc.Height=H;
    sd.BufferDesc.Format=DXGI_FORMAT_R8G8B8A8_UNORM;
    sd.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;
    sd.OutputWindow=hw;
    sd.SampleDesc.Count=1;
    sd.Windowed=TRUE;
    if(FAILED(D3D11CreateDeviceAndSwapChain(0, D3D_DRIVER_TYPE_HARDWARE, 0, 0, 0, 0, D3D11_SDK_VERSION, &sd, &swp, &dev, 0, &ctx)))ExitProcess(1);
    ID3D11Texture2D* bb=0;
    IDXGISwapChain_GetBuffer(swp, 0, &IID_ID3D11Texture2D, (void**)&bb);
    ID3D11Device_CreateRenderTargetView(dev, (ID3D11Resource*)bb, 0, &rtv);
    ID3D11Texture2D_Release(bb);
    init_depth_shadow();
    init_rts();
    init_states();
    cb_make(&scene_cb, sizeof(SceneCB));
    cb_make(&object_cb, sizeof(ObjectCB));
    cb_make(&user_cb, sizeof(UserCB));
    init_shaders();
    init_prims();
    LARGE_INTEGER fq, t0, tn;
    QueryPerformanceFrequency(&fq);
    QueryPerformanceCounter(&t0);
    float sec=0;
    MSG msg;
    for(;;) {
        while(PeekMessageA(&msg, 0, 0, 0, PM_REMOVE)) {
            if(msg.message==WM_QUIT)ExitProcess(0);
            TranslateMessage(&msg);
            DispatchMessageA(&msg);
        }
        QueryPerformanceCounter(&tn);
        sec+=qpcdt(&tn, &t0, &fq);
        t0=tn;
        render(sec);
    }
}

